### ISSUE TITLE
Table demo should have an example with controls

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#110]
The question "how do I add checkboxes to each row of a table" has come up a few times, so presumably it'd be helpful to have that example in the demo, with code.

**Comment by aforemny** [comment]
Implementation is underway in [elm-mdl/bug-110](http://github.com/aforemny/elm-mdl/tree/bug-110).

**Comment by debois** [comment]
I didn't try to run it, but from the source, it looks good?

**Comment by aforemny** [comment]
Yes, we can merge it. Please go ahead if you want to.

**Comment by debois** [comment]
Great! I'll merge it tomorrow.

I don't think there's any ham in improving on upstream like that.
