### ISSUE TITLE
Menus don't register onSelect when clicked on the very left (right) of an item

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#112]
The current demo for menus has an `onSelect` handler on some child node of a menu item. If you click on the very left (or very right) of a menu item, that handler is not triggered because of the padding on the menu item itself.

**Comment by debois** [comment]
After merging #133 and we-working the onSelect API, I can reproduce this in neither Chrome, Firefox, nor Safari. Closing for now, if someone re-discovers it, we can re-open.
