### ISSUE TITLE
Button Ripple does not vanish in IE

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#114]
Testing a site in IE 11 (works fine in Chrome, Firefox, and Edge), and the buttons ripple does not vanish, any button.  It does the effect when clicked but then the slightly grayed out ripple stays instead of vanishing, sometimes the ripple does not even go all the way across the button and instead just stops there, sitting.  Checking the CSS in the DOM on the page shows that the "is-visible" class is still on the ripple, yet is not on the buttons that are not yet touched, but once touched they get "is_visible" added and never removed.  If I remove it manually via the IE11 javascript console then they look correct again until the next time it is clicked, where the ripple will animate but then not vanish.

**Comment by OvermindDL1** [comment]
Testing via https://debois.github.io/elm-mdl/ in IE 11, same issue, the ripple div is not set invisible once the animation is complete.

However, it does work properly at https://getmdl.io/components/index.html#buttons-section thus something is missing in this port?

**Comment by debois** [comment]
Just to be sure: This is on 6.0.4?

**Comment by OvermindDL1** [comment]
Correct, from my elm-stuff/exact-dependencies.json:
```json
    "debois/elm-mdl": "6.0.4",
```

**Comment by debois** [comment]
Fixed in 6.0.5.
