### ISSUE TITLE
Menu bug placement

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#119]
So other than the bug of the Menu's not closing when clicked outside of them, found two other bugs.

Both bugs are demonstrated at:  https://overminddl1.com/screenshots/work/MDL-Menu-Bug0.gif
Image inline (as it is surprisingly small in file size, though may be hard to see):
![Bug example](https://overminddl1.com/screenshots/work/MDL-Menu-Bug0.gif)

1. The first bug is that I do not see a way to override its action, I need to add `{ stopPropagation = False, preventDefault = True }` because the overall elm app is embedded in a form tag (old template that I do not control so cannot fix), thus when the menu is clicked it will show the menu, however it then also reloads the page, which is a rather bit jarring...  You can see it happen in the gif, the menu does appear but then the page reloads.  The onClick is defined in that file, and could easily be overridden at:  https://github.com/debois/elm-mdl/blob/master/src/Material/Menu.elm#L514

2. The second bug is that the menu is not appearing at the menu button.  Here is the code:
  ```elm
  Grid.cell
    [ Grid.size Grid.All 1
    , Options.cs ("messenger-input-options-menu-container messenger-input-options-menu-"++classname++"-container")
    ]
    [ Menu.render Mdl pidx mdl
        [ Menu.topRight
        , Menu.icon iconname
        --, Menu.ripple -- Commented because Ripples break tooltips for some reason...
        , Options.cs ("messenger-input-options-menu messenger-input-options-menu-"++classname)
        , Tooltip.attach Mdl (pidx++[0])
        ]
        items
    , Tooltip.render Mdl (pidx++[0]) mdl [] [ text name ]
    ]
  ```
  And yet it is not only appearing in the `Menu.topRight`, but rather it is appearing in the far lower-right corner of the page, as seen in the graphic.

**Comment by OvermindDL1** [comment]
I tested shrinking the page, the menu actually appears in the lower-right corner of the visible screen, regardless of where scrolled.

**Comment by debois** [comment]
# Click propagation (1)

I'm not sure how to deal with this generally. It seems we want the ability to tell any elm-mdl component whether or not it should propagate its clicks (which may be internal actions), or alternatively, always suppress clicks. The former seems cumbersome, API-wise, and I can't help feeling that the latter will overly constrain users (events bubble for a reason). I'd appreciate other people's thoughts here (@aforemny, @vipentti)?

## Workaround
You can catch the click it and stop it higher up the DOM, by installing an `onWithOptions "click"` handler on one of the parent elements of the Menu. 

# Menu placement (2)
This is likely the bug debois/elm-dom#4; try [this workaround](https://github.com/debois/elm-mdl/issues/93#issuecomment-234567268) from the related #93.

**Comment by OvermindDL1** [comment]
## 1
I have actually already tried the onWithOptions "click" in a higher part of the DOM, but oddly enough it broke only the MDL Toggle, everything else seemed to keep working except the Toggle.  The Toggle would send MDL messages but my Toggle.onClick never sent a message again and I could not for the life of me figure out why, so I had to revert it...  >.>

##2
Testing the workaround now, however I walked through the entire DOM tree from the visible menu to the body and not a single element has overflow on it.  Placed `position:relative;` on every single DOM element in the entire tree from the parent of the menu to the body and no change.  Added it to the menu div itself as a test and it moved it to overlap the menu button while pushing everything below it much further down.  Via playing with the CSS on the menu DOM div, if I remove the right and bottom properties then it places it nicely below the button without pushing stuff around (but considering it defaults to its set position then, it makes sense...)

I've also noticed that clicking on the menu items does not make the menu vanish.  Clicking outside the menu does not make the menu vanish.  Have to actually click on the button itself to toggle the menu off and on.

**Comment by debois** [comment]
Could you provide a link to a repo so we can try this out? Or even better, a shortest-possible failure example?

**Comment by OvermindDL1** [comment]
The repo is currently internal to work so unable to do that, will see if I can try to replicate a simple example though if I get enough time.

**Comment by OvermindDL1** [comment]
I cannot even get elm-mdl to work in the elm reactor at all, no css (I've never used elm reactor so I could very likely be doing something wrong...)...

**Comment by debois** [comment]
I don't think elm-reactor knows how to recognize elm embedded in a .html file, but I may be wrong.  When I work with the elm-mdl demo, I run .elm files directly from elm-reactor, loading my CSS using this trick:

    node "style"
      [ type' "text/css"]
      [ Html.text """
           @import url("http://link.to/my/stylesheet.css");
        """
      ]

This gives you an annoying flicker at load, but I think elm-reactor is worth it (for development).

**Comment by OvermindDL1** [comment]
It would be, but my Elm app has tight integration with Phoenix websockets and using the reactor would be cross-site websocket requests that would be missing the CSRF to boot, so it becomes a little difficult to use.  :-)

**Comment by debois** [comment]
Ah.

At this point, this issue is about at least two, maybe three things; I'm confused about exactly which. I'll close this; could you open separate issues for each problem that remains in 7.0.0?

**Comment by OvermindDL1** [comment]
Certainly, if only the core elm devs were as responsive as you.  :-)

*cough*[cough](https://github.com/elm-lang/core/issues/612)*cough*

**Comment by debois** [comment]
Thanks—appreciate it :)

(But to be fair: I think way fewer issues in core has solutions along the lines of "add or remove this simple piece of CSS". ;)

**Comment by OvermindDL1** [comment]
Heh, well the linked bit has a simple fix (maybe hack), just test if the 'root' is null, if so then early return.  Right now it completely and randomly kills the entire elm app requiring a page load.  ;-)
