### ISSUE TITLE
Toggles Demo issue

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#125]
The [Toggles Demo](https://debois.github.io/elm-mdl/#toggles) has an issue where if you turn on "Auto-increase" at the bottom, then switch away from the tab to another, then back again, it doubled the rate, then go to another tab and back again, it is now tripled, and so on and so forth.

**Comment by OvermindDL1** [comment]
This was tested on Chrome.

**Comment by OvermindDL1** [comment]
Actually after further testing I think clicking 'Increase' while it is auto increasing increases its rate instead while also adding 1?  Interesting.

**Comment by OvermindDL1** [comment]
Yeah this looks like it could be a bug in the Helpers.delay function actually?

**Comment by OvermindDL1** [comment]
Or it could be be designed that each time increase is clicked then it adds yet another persistent timer?  Might be good to add a touch of docs about why/how the Demo works if that is the case?  :-)

**Comment by debois** [comment]
I fixed the single-increase-doubles-the-rate bit (try it out [here](https://debois.github.io/elm-mdl/wip.html#toggles).

I couldn't reproduce the behaviour on tab-switching. Can you provide exact steps to make this happen?

**Comment by OvermindDL1** [comment]
Sure, posted more in #124 about it along with image examples.
