### ISSUE TITLE
Chevrons in tabbar disappear when resizing

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#127]
Original reported by @Overminddl1 in #124: 

Also another image.  I know these are not 1-to-1 comparison of components but demonstrating changes on the elm-mdl demo site compared to the getmdl demo site and how they handle resizing:
![Resizing differences](http://overminddl1.com/screenshots/work/MDL-Tab-Scroll-Chevrons.gif)

**Comment by OvermindDL1** [comment]
> In the meantime, on mobile and on mac, the tabbar scrolls when you swipe it.

That 'could' work on desktop, however it just selects text currently when you try that.  Still good to have some kind of fallback too.  :-)

**Comment by debois** [comment]
It's a bug in upstream google/material-design-lite#4329. It's already fixed there google/material-design-lite#4518, but hasn't been released yet. I fixed it directly in elm-mdl.

**Comment by OvermindDL1** [comment]
Ah, that was a simple commit on their part, cool.  :-)
