### ISSUE TITLE
API for onClick in menu is inadequate

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#129]
Separated out from #121:

From https://github.com/debois/elm-mdl/issues/121#issuecomment-235928524:

> the onClick handler on the #112 part is not per-element, I need each element to have their own message handler, in this case I think the onClick on the menu Items should be removed. If someone wants it to be clickable and send a message then they should do that in their own Item's HTML. So perhaps this should be re-opened to remove the default onClick handler on the Menu Items as it seems superfluous (it is not even used in the Demo, Item-specific handlers are).

From https://github.com/debois/elm-mdl/issues/121#issuecomment-235971921: 

> Actually the onClick handler on a menu could be left, but remove it from the Items and instead put it on the menu open/close. Being able to react to when the menu is opening and closing would be very useful for a menu I just made here.

@OvermindDL1: I moved this here to keep issues separate. 
@aforemny: I'm not entirely following this; is it important enough it needs to go in v7?

**Comment by OvermindDL1** [comment]
It is a fairly irritating user-interface bug.  I would *love* a way to remove the implicit on-click handler on the menu's (and be able to take up the full menu width my items), and would love to be able to react to the menu button expand/close (no matter how it is closed).

**Comment by aforemny** [comment]
@debois: I would like to have this solved in v7. But I do not have a solution for it yet. Possibly, we could make the menu listen to the `mouseup` event, and let the user handle the `click` event? Better yet (but still a hack), could we dispatch `mycustomevent` on click and handle that internally, similar to the ripple hack? Or wouldn't it work with Elm only being able to listen to GlobalEvents?

If anybody wants to fix that, please go for it as I am restricted on time currently. If anybody is interested, he/she might want to work off my better-menus branch as it includes a few fixes and keyboard control already.

**Comment by debois** [comment]
@aforemny: I'll look at this. Is your better-menus branch in a state where I can merge it? Does it have commits indicating what issues it already fixes?

**Comment by OvermindDL1** [comment]
Honestly I'd prefer if the menu items did not handle clicks at all, let the users own html in the items handle those.  What I would like is for onClick on the menu to be called when the menu is opened (maybe an onOpen and/or onClose callbacks)?  It would be nice to have a websocket filled-in list only filled in if the menu is accessed to prevent needless round-trips in the majority of the time.

**Comment by debois** [comment]
But menu items should ripple?

**Comment by OvermindDL1** [comment]
I would personally say no on that too, the user html can do that itself if they want.  I would say either a menu should be simplified so the user can show and manage whatever they want as the items (including their own disabled status and callbacks), or it needs to be locked down to not allow any custom html and just be a simple defined format (such as text, icon-on-the-left, or both), with per-item callback messages (this is more work for this mdl library and reduces capability though).
