### ISSUE TITLE
Textfield should support more DOM event handlers

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#130]
From @OvermindDL1 at https://groups.google.com/d/msg/elm-discuss/pNPVxrz_jlE/z_zaaattAwAJ : 

> Do not see an example or demonstration code that shows this, but how can I get an Enter keypress from a single line `Textfield`, and how can I distinguish it from a Shift+Enter keypress in a multiline `Textfield`, or how can I get the event data?

**Comment by OvermindDL1** [comment]
Yeah there does not seem to be a way to set generic `on` handlers like in Html.Events, and it is playing havoc with my ability to get data...

**Comment by vipentti** [comment]
@OvermindDL1 I'm currently working on this; Are you simply looking for `onEnter` or would `onKeyUp` work? What kind of use case are you looking at ?

Currently thinking something like
```elm 
-- Event
type alias KeyEvent =
  { shift : Bool
  , keyCode : Int
  }

-- In your own update Add event listener 
  | KeyUp Textfield.KeyEvent

-- To component as well 
   Textfield.onKeyUp KeyUp

-- Then in update 

  KeyUp { shift, keyCode } ->
      case keyCode of 
        13 -> if shift then "shift + enter" else "just enter"
        _ -> ""

```

This does not stopPropagation and does not preventDefaults so if you want to actually intercept enter and prevent that from adding new lines that does require some extra functionality.

**Comment by OvermindDL1** [comment]
Something like onKeyUp would be perfect, I do have plans for some extra things later.  I would *especially* love if the KeyEvent also had a selection range, something like:
```elm
type alias KeyEvent =
  { shift : Bool
  , keyCode : Int
  , selection_range : { start : Int, end : Int }
  }
```
Right now I have to get the selection range onChange via a port, which is hacky since I cannot make my own `on` events right now to do custom json decoding of the event (would love that!)

**Comment by debois** [comment]
@vipentti: Is there some way we can avoid duplicating large parts of `Html.Event`?

**Comment by OvermindDL1** [comment]
If there is some way in the API to drop a lot of the Material specific html things and use Html.* itself that would be best.  Making my own 'on' handlers again would be fantastic.

**Comment by vipentti** [comment]
Support for custom events should be available for Textfields now.

**Comment by OvermindDL1** [comment]
Having a way to have custom event handlers on any type would be fantastic though, like normal `elm-html`.  I have to keep changing back to Html stuff and hacking in material things into it for my onScroll events for example.  ^.^

**Comment by debois** [comment]
Fixed in [7.3.0](https://github.com/debois/elm-mdl/releases/tag/7.3.0); nice example use [here](https://debois.github.io/elm-mdl/#textfields) (last example).

@OvermindDL1: Are you aware of `Options.attribute`? You can use it with `Options.div` et. al. to install arbitrary attributes on styled Html elements:

```elm
    Options.div 
      [ Options.attribute <| Html.onClick MyClickEvent ]
      [ text "I'll know if you click me!" ]
```

**Comment by OvermindDL1** [comment]
Ah I was wondering what that was for.  Is there no way to iterate over the attributes and remove user supplied 'onBlur' and such things, or to hoist them 'into' your callback so both get called?  That way getting rid of the Options special stuff entirely?

**Comment by vipentti** [comment]
I had some ideas about adding support for user defined events on a larger scale but haven't had a time to experiment with it yet.

**Comment by debois** [comment]
That'd be awesome! I'd love to be part of discussing how to do that also, here or on slack :)
