### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by george-ayris** [debois/elm-mdl#135]
Hi there,

I was having problems installing the package in my current project, so I tried installing in a completely blank project and hit the same error:

`Error: Unable to find a set of packages that will work with your constraints.`

Here's a log of me reproducing the error:

![image](https://cloud.githubusercontent.com/assets/9038126/17384399/da029e1a-59d3-11e6-81de-cbf766838875.png)

Any ideas what I might be doing wrong?

Cheers,
George

**Comment by OvermindDL1** [comment]
It was literally 'just' uploaded.  Probably had not reached your mirror yet (though it probably has now), try again?  :-)

**Comment by george-ayris** [comment]
Thanks, but unfortunately I'm still getting the same error. 

I tried deleted the debois/ folder in my global .elm folder and that had no effect.

I also tried manually installing all the dependencies (at the versions in the project's elm-package.json) and also still getting the error.

Any more suggestions?

**Comment by debois** [comment]
You have to be on elm-version 0.17.1 (second-last line of your elm-package.json). Does that help?

**Comment by jalehman** [comment]
Just ran into this issue myself -- upgrading elm to 0.17.1 fixed the issue for me.

**Comment by george-ayris** [comment]
Thank you very much. Upgrading elm using npm worked a treat (though setting the minimum version in the elm-package.json didn't seem to have a visible impact). Also, thanks for taking the time to port mdl to elm.

**Comment by debois** [comment]
Very welcome :)
