### ISSUE TITLE
Fixed drawer toggles scrollbar 

### ISSUE THREAD

**Issue by anfelor** [debois/elm-mdl#136]
1. Go to https://debois.github.io/elm-mdl/#layout
 2. Enable Fixed drawer
 3. Click on "Card component" in the drawer
 4. Try to scroll :-)

Tested: Firefox and Chrome on Linux

**Comment by debois** [comment]
I can't reproduce this on Chrome, Firefox on Mac OS. Can you say a little bit more about what goes wrong? I'm not sure what you mean "toggles scrollbar"?

**Comment by OvermindDL1** [comment]
I can reproduce it following his steps precisely, see attached image:
![demo image](https://overminddl1.com/screenshots/work/MDL-Layout-Bug0.gif)
See when 'Card Component' is clicked then the scrollbars disappear in the menu view area on the far right.

**Comment by OvermindDL1** [comment]
Chrome on windows 10.

**Comment by OvermindDL1** [comment]
For note, I was trying the scrollwheel too, no movement on screen.

**Comment by debois** [comment]
Please ignore the above reference; should have been to #156.

**Comment by debois** [comment]
This is likely a logic arrow in Layout. @vippenti, I'd like to take over this unless you're already deep inside it?

**Comment by vipentti** [comment]
Feel free to take over
