### ISSUE TITLE
Tabs don't fit on screen

### ISSUE THREAD

**Issue by anfelor** [debois/elm-mdl#137]
Since the number of tabs in the elm-mdl demo increased, not all fit on my 1600x900 screen anymore:
![04-08-2016_15 34 05](https://cloud.githubusercontent.com/assets/16764214/17403742/61bd195e-5a59-11e6-88b4-490d9b697a9d.png)

With fixed tabs:
![04-08-2016_15 34 09](https://cloud.githubusercontent.com/assets/16764214/17403743/61be34d8-5a59-11e6-8e1b-bcaa030dc343.png)

Here is how it should look:
![04-08-2016_15 34 00](https://cloud.githubusercontent.com/assets/16764214/17403741/61ba8dd8-5a59-11e6-9b43-6b368c210ec8.png)

**Comment by debois** [comment]
Should be fixed; could you check the [demo](https://debois.github.io/elm-mdl/)?

**Comment by OvermindDL1** [comment]
Seems to work better for me (really elm has no way to get the internal width of a generated div even after a frame of view?  Could use a port for it I guess but ick...).

**Comment by anfelor** [comment]
Demo looks alright.
