### ISSUE TITLE
Shouldn't plain buttons be colourless?

### ISSUE THREAD

**Issue by anfelor** [debois/elm-mdl#138]
In the [Google MDL](https://getmdl.io/components/index.html#buttons-section) plain buttons are gray, while colored buttons are pink (the primary color?). In the elm-mdl demo, however, they seem to be identical, as the plain buttons also have the `mdl-button--colored` class.

**Comment by debois** [comment]
Thanks! Turns out `Button.plain` had a bug. I fixed it in f8789bfb86c28ef0072730d9e282874bc927cbd1 and in the [demo](https://debois.github.io/elm-mdl/#buttons). The fix will be out in 7.0.1.
