### ISSUE TITLE
Demo page doc link 404's in Menu

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#139]
On the Demo page, the Menu section of https://debois.github.io/elm-mdl/#menus if you click "Package documentation" it takes you to http://package.elm-lang.org/packages/debois/elm-mdl/7.0.0/Material-menu that does not exist.

**Comment by OvermindDL1** [comment]
For note, it should be:  http://package.elm-lang.org/packages/debois/elm-mdl/7.0.0/Material-Menu

**Comment by debois** [comment]
Fixed, thanks.
