### ISSUE TITLE
Menu not closing when clicked outside

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#140]
As of elm-mdl version 7.0.0 still none of the Menu's on my site are closing when clicked outside of the menu, you have to click the menu button again to close it or click a button inside the menu to close it, but clicking outside the menu does not close it.

**Comment by debois** [comment]
Can't reproduce this. Can you confirm you see this behaviour on [the demo](https://debois.github.io/elm-mdl/) and let me know what browser you're on?

**Comment by OvermindDL1** [comment]
It does work on the demo, which is why I am curious as to why it is not working in my app.  Latest release chrome as of yesterday on Windows 10.

Testing others, same issue in Firefox, IE11, and MS Edge, they all do not close the menu when clicking anywhere except in the menu or on the button (and they all are also putting the menu in the lower-right corner of the parent-most container).

**Comment by OvermindDL1** [comment]
I was perusing the Menu.elm source and noticed it should close the menu via receiving a mouse click outside of it and listening.

*However*, in debug mode I log all of my messages, and I of course have a huge amount of 'Mdl' messages, however there is no Mdl message sent when I click in random places on the page, thus implying the Mouse is not being listened to somehow.  Probably a bug in the Mouse package?

**Comment by OvermindDL1** [comment]
Further testing by manually injecting into the elm generated javascript to add a click handler seems to fix it, so yeah it looks like an elm-lang/Mouse bug?  That is not certainly something I am going to do every recompile though, if anything I'd fix the elm-core crash bug instead and even that is painful to do every recompile.  ^.^

**Comment by OvermindDL1** [comment]
And I added a Mouse.clicks subscription to my main app and I get those messages fine, but still nothing while a menu is open.  The Menu.elm code looks like it is subscribing to it when needed, but maybe there is a bug there?

**Comment by debois** [comment]
You did hook up the `Menu.subs` subscription?

**Comment by OvermindDL1** [comment]
Ah, I've not noticed that in the changeover docs.  Might I recommend the style I made with my Helpers library?  For a few weeks its been operating like this:
```elm
import Helpers

type alias Model =
    { helpers : HelpersModel Msg
    , mdl : Material.Model
    , other stuff..

init programFlags locationResult =
    let
        model' : Model
        model' =
            { helpers = Helpers.init Helpers
            , mdl = Material.model
            , programFlags = programFlags
            , other stuff...



type Msg
    = Helpers (HelpersMsg Msg)
    | Mdl (Material.Msg Msg)
    | other stuff....


update msg model =
        case msg of
            Helpers helpersMsg ->
                let
                    ( helpersModel, helpersCmd ) = Helpers.update Helpers helpersMsg model.helpers
                in
                    ( { model | helpers = helpersModel } , helpersCmd )

            Mdl mdl_msg ->
                Material.update mdl_msg model

            other stuff..... ->


subscriptions model =
    Sub.batch
        [ Helpers.subscriptions Helpers model.helpers
        , other stuff......
```
And so forth, it has supported every need I've had and every new helper function that I add to it.  For example:
```elm
-- Get selected text from text input or field and return the entire text with the selected part surrounded
surroundSelectionWithInputMsg : String -> String -> String -> Cmd Msg
surroundSelectionWithInputMsg pre body_default post =
    Cmd.batch
        [ surroundSelectionWith Helpers
            { selector = messageinput_selector
            , pre = pre
            , body_default = body_default
            , post = post
            , portname = "port_MessageOptionCB"
            , cb_data = Nothing
            }
          -- , focus_messageinput
        ]

port port_MessageOptionCB : (Helpers.SurroundCB {} -> msg) -> Sub msg


-- Focusing an element:
focus_messageinput : Cmd Msg
focus_messageinput =
    cmd_onNextFrame Helpers <| focusElem Helpers messageinput_selector



-- Another example, I have this in one of my update command message outputs:
                    , Cmd.batch
                        [ scrollScrollable Helpers Scrollable_Bottom ".messenger-mesglist"
                        , focus_messageinput
                        ]


-- I can delay a message an update cycle and it will be re-broadcast here:
                    , Helpers.cmd_delay Helpers MyMessage

-- Or I can even delay it a render frame (needed especially so I can 'focus' things properly)
                    , Helpers.cmd_onNextFrame Helpers MyMessage
```
And a variety of other things (I could/should simplify the Helpers.update stuff but meh, I've not cared yet).  So how about making a something like this for elm-mdl:
```
subscriptions model =
    Sub.batch
        [ Helpers.subscriptions Helpers model.helpers
        , Material.subscriptions Mdl model.mdl
        , other stuff......
```
That way you can handle subscriptions for things like the menu, or whatever else may be required in the future as well?  Would be nicer than adding subscriptions for each thing like Menu or whatever else may be added over time?  :-)

**Comment by OvermindDL1** [comment]
And yep, adding `Menu.subs Mdl model.mdl` fixed it.  It looks like Layout has its own version as well, I'd definitely say combine all those to a central Material.subscriptions or so like my Helpers library works.  :-)

**Comment by debois** [comment]
Yes, quite. I'll have to think a bit about this. 

Currently, only layout and Menu have subscriptions, so it shouldn't be too bad for now, but you're right, others might follow.
