### ISSUE TITLE
Menu button ripple not working

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#141]
As of elm-mdl version 7.0.0 the button that opens the menu does not ripple although the menu is specified as:
```elm
Menu.render Mdl
                pidx
                mdl
                [ Menu.topRight
                , Menu.icon iconname
                , Menu.ripple
                ]
                items
```

**Comment by debois** [comment]
This is upstream-behaviour. The ripple option applies only to items.

**Comment by OvermindDL1** [comment]
Hmm, any chance to get it on the menu fob as well then?  The inconsistency in my UI bugs me.  ^.^
