### ISSUE TITLE
Menu items rippling without being set, and are accepting clicks with no click handler set

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#142]
As of elm-mdl version 7.0.0 the menu items themselves are rippling when they should not be.  My menu's are defined as:
```elm
Menu.render Mdl
                pidx
                mdl
                [ Menu.topRight
                , Menu.icon iconname
                , Menu.ripple
                ]
                items
```
Where each item is defined as:
```elm
view_msg_inputarea_options_btn_menu_item divider enabled pidx mdl name iconname msgType =
    Menu.Item
      [ if divider then Menu.divider else Options.nop
      , if enabled then Options.nop else Menu.disabled
      ]
      [ Button.render Mdl
          pidx
          mdl
          [ Button.ripple
          , button_onClick msgType
          ]
          [ Icon.i iconname
          , text name
          ]
      ]
```
So both my button ripples, **and** the background of the menu item ripples distinctly.  The menu item itself also seems to send no onclick message, nor should it since that should be handled by my button, or the button should be disallowed and it should be handled by the item.  It seems the 'ripple' property on the menu does not apply to the menu button, but rather the menu items, so no way to set them individually.
![bug demonstration](https://overminddl1.com/screenshots/work/MDL-Menu-Bug1.gif)

**Comment by debois** [comment]
The duplicate ripple will be fixed in a shortly upcoming point release. 

You might want to consult the Material Design specification on [menus](https://material.google.com/components/menus.html#menus-menu-items)—I'm not sure you're supposed to put controls beyond checkmarks in lists.
