### ISSUE TITLE
Demo Dialog package docs incorrect URL

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#146]
https://debois.github.io/elm-mdl/#dialog when clicking the Package Documentation link goes to http://package.elm-lang.org/packages/debois/elm-mdl/7.0.0/Material-Card instead of http://package.elm-lang.org/packages/debois/elm-mdl/7.0.0/Material-Dialog

**Comment by slegrand45** [comment]
See #145 :smiley:

**Comment by debois** [comment]
:)
