### ISSUE TITLE
Component suggestions

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#147]
It would be highly desirable for new components to be added over time that follow the same style and usage patterns as the ones currently existing here.  Thus I have some ideas (that I may on occasion do or for someone else who wants an idea of something to do):
- When I refer to the 'user' I refer to the user of elm-mdl, not of the end-product.
- [ ] **Accordion** - Useful set of buttons that expand to a detailed view while hiding others in the same set.  Should be fairly easy to build too.
- [ ] **ButtonGroup** - Group of buttons that can be pressed/unpressed, optionally forcing only one to be able to be depressed at a time, think of it is a group of checkboxes or radioboxes depending, but in button form (for text, icons, both, whatever).  This is a popular design in many Material styled websites that I've seen.
- [ ] **Calendar** - With configurable start/end (so we can link two together to define a date range).  A default set of options would be for Date, Time, or setting both as a DateTime with a button to specify 'now' (perhaps a use-configurable set of buttons/menu).
- [ ] **Listfield** - A standard drop-down list (or optionally expanded) with a search at the top to refine what is displayed
- [ ] **Dropdown** - A generic Dropdown hint, basically just something that reacts to something else by  displaying a user-defined element.  The user can define whatever they wish, a simple single item, a list, an entire interface, whatever they wish.  Optional auto-closing when clicked outside of it.  Other options such as opened relative to like the current Menu does with perhaps other options.  This could be used to allow the user themselves to implement things such as the existing Menu by attaching a dropdown to a button, or pop-up a Calendar when an inputbox is focused, or whatever else can be thought of.  The existing Menu could be implemented as a refinement of this dropdown, as could other components.
- [ ] **AsyncImage** - An image that is only loaded when the page goes to the location of the image.  On image heavy pages these are a necessity to prevent the page from bogging down during loading of many images, especially as not all will be viewed so there is no point in fetching them.  The size should be specified (optionally?) and perhaps with an optional effect for when it is loaded (a fade-in or slide-in are the most common used).
- [ ] **InplaceInput** - An user-defined element that when clicked is replaced with a user-define editor, whether a simple text input element or something as fancy as a full user interface (like markdown perhaps), whatever the user wants.
- [ ] **Tags** - A tag interface allowing for adding user-specified tags.  Should probably be something like the afore-mentioned Listbox on something user-definable (default input textbox perhaps?) with a searching functionality that refines appropriate tags, optionable on whether new tags are allowed or not.  It absolutely should allow for a data model that is based on some index (just a string should work) and optionable extra data so as the search is refined the listbox can show specific data about the tag being selected.  Thing being able to type in the tag box 'elm' and see in the dropdown that appears the 'elm' tag along with a grayed out description of it (or whatever the user wants to show).  When selected the tag should be removed from the box and added to a list (the usual style as seen online) or so.  Many ways this can be gone but looking at other Material websites and copying their style should be done.
- [ ] **ResizableTextarea** - This could perhaps be an option on the existing multi-line text area, have it be able to dynamically resize based on its content.  In javascript this is usually done by putting the text in the same font on an unattached 'div' with the same width, then reading back its height and setting the textbox to that size + extra to account for more typing.  I am unsure how to do this in pure-elm but at the very least adding a way to allow the user to hook-up a built-in port might be useful.
- [ ] **RelDateTime** - A component to show a date/time as a relative value like "About 30 seconds ago" or "About 12 days ago" or so.  I have an existing one that I use already so I might move it out and submit it here.  It also has a Tooltip that shows the precise DateTime when hovered over and it updates all globally once a minute while showing the 'About' within a 2 minute variance (I.E. for <2 minutes it shows "< 2 minutes", for each minute after it shows "About X minutes ago" up to <2 hours ago, where it repeats the pattern up to years).
- [ ] **DraggableList** - Think the Github 'task list' how you can drag using the movement bars to a different place.
- [ ] **Tree** - Not just like a file manager explorer view, but it could all be configurable, `Icon`s for the expand/collapse if enabled at all, could just be a straight static tree, could look like a nested list, etc...
- [ ] **Bordered Fields** - Possibly just a wrapper, but something to 'pop-out' fields that it contains, could be a generic 'Border' that you can set elevation on, though I am unsure how that would differ from an equivalent div with an elevation.  Perhaps remove this?
- [ ] **Element Query Grid** - The default mdl Grid is a Media Query Grid, it resizes based on the screen size only.  An Element Query Grid resizes based on both screen and element sizes.  See demo at:  http://leifoolsen.github.io/mdl-ext/demo/grid.html
- [ ] **Carousel** - A manually or automatically (timed/event) controlled carousel that can hold other arbitrary elements, similar functionality to a tabbar but can be automated, generally used for Pictures with possible overlaying text.
- [ ] **Lightboard** - A Flowing box of images, useful to be clicked on to bring up a Lightbox.
- [ ] **Lightbox** - A page popup for large size viewing of an element, traditionally images but could be other things (think the Chrome web store).  Clicking outside of it would close it.
- [ ] **SelectField** - A SelectField like the ListField above but replaces a stock `<select>` element with an optional `<input>` base to add new elements if that is allowed.
- [ ] **Sticky Header** - Add a new function to the standard Navigation header to allow it to by more 'Sticky', I.E. allow it to scroll up slower than the page so it is not an immediate jump, a demo is at http://leifoolsen.github.io/mdl-ext/demo/sticky-header.html and more can be seen in the Sticky Header section on the Accordion on the left.

If there are other ideas it might be good to put them here as well to put such ideas in a singular place.  :-)

**Comment by Lesuk** [comment]
**RelDateTime** ("About 30 seconds ago") - waiting for this.
@OvermindDL1  can you implement this first (or share with your code)?

**Comment by OvermindDL1** [comment]
@Lesuk I have been thinking of PR'ing mine, however it would require either a subscription (easier now that we have a master subscription) or would require the user to manually update it however often they themselves want, probably the subscription one would be better (perhaps they can specify 0 for update time to disable so they can do it manually).

However right now this is my code that handles the 'meat' of the calculations, pretty simple (it is the wrapping stuff around it that is more code):
```elm
toRelTime : Time -> Time -> String
toRelTime curTime prevTime =
  let
    diff_minute =
        Date.Extra.diff Date.Extra.Minute prevTime  curTime 

    diff_hour =
        Date.Extra.diff Date.Extra.Hour prevTime  curTime 

    diff_day =
        Date.Extra.diff Date.Extra.Day prevTime  curTime 

    diff_month =
        Date.Extra.diff Date.Extra.Month prevTime  curTime 

    diff_year =
        Date.Extra.diff Date.Extra.Year prevTime  curTime 

    s_diff =
        if diff_minute < 2 then
            "<2 minutes ago"
        else if diff_hour < 2 then
            "About " ++ (toString diff_minute) ++ " minutes ago"
        else if diff_day < 2 then
            "About " ++ (toString diff_hour) ++ " hours ago"
        else if diff_month < 2 then
            "About " ++ (toString diff_day) ++ " days ago"
        else if diff_year < 2 then
            "About " ++ (toString diff_month) ++ " months ago"
        else
            "About " ++ (toString diff_year) ++ " years ago"
  in
    s_diff
```
I am very much an Elixir programmer, which loves _ instead of camel-case, but I would fix it to Elm style if I PR it.  It uses the Date.Extra library (one of them, the one with diff because I am too lazy to re-implement it myself, though I would re-implement it myself if I PR it).  I just stuff that into a span with an elm-mdl Tooltip to show the full date though.  I set up a subscription of `Time.every Time.minute RequestTimeUpdate` to update it once a minute.  For a PR I would have that be user configurable and they could specify the resolution of the relative time string.  If I get time from work I shall PR it though.  :-)

**Comment by Lesuk** [comment]
@OvermindDL1 Thank you for sharing!

**Comment by OvermindDL1** [comment]
I am thinking more about Material entirely.  Material encompasses a *lot* more than just what MDL does, including guidelines for all sorts of things.

As for i18n, I've not clue how that is supposed to be handled in Elm, I've been ordered at work to not care about i18n so I've not looked...  I could imagine a dictionary of 'existing values' to 'translated values' would work though, defaulting to the existing if the translated does not exist?

**Comment by OvermindDL1** [comment]
For reference, there is an `mdl-ext` addon library for `mdl`, the demo of which is at:  http://leifoolsen.github.io/mdl-ext/demo/

It adds the Accordion, Bordered Fields, an Element Query Grid instead of just a Media Query Grid, allowing for much greater Grid resizing control, Image Carousel, Lightboard, Lightbox, a Materialized SelectField, and a Sticky Header, which is just the normal header but it goes off the screen as the page is scrolled instead of instantly at a point.

**Comment by debois** [comment]
As always, we'd consider a PR :)

**Comment by OvermindDL1** [comment]
Yep, I am planning on PR's once I get time from work.  Currently I am using this issue as a documentation and idea thread of what could be added for me or someone else to PR.  :-)

**Comment by OvermindDL1** [comment]
Sooo, this thread was not even an early jump.  The upstream mdl library is having a lot added to it in its v2 overhaul as seen at https://github.com/Google/material-design-lite/issues?q=is%3Aissue+is%3Aopen+label%3Av2-component and as such elm-mdl should support those as well.  It seems that all of the changes are not only nice and warranted but highly functional.  Should probably start bringing in those soon.  It also includes most of what I listed above as well so those are going to be stock mdl soon.

**Comment by vipentti** [comment]
Once MDL v2 is in beta or at least has all of the current components implemented I think we can start the porting work to update to the eventual v2. But before that there will likely be quite a few breaking changes, also the current v2 branch has only a few actual components implemented

**Comment by OvermindDL1** [comment]
The link to the spec should be 'done' now though, mdlv2 is just making it now is the thing.  The current Material spec is what Google's new operating system is being made to so it should be very well set and ready to copy now.  If anything I'd say rename this library to elm-material (the main namespace is `Material` after all) and make it follow the Material spec itself instead of mdl.  In comparison, `mdl` itself is slow moving, especially since the spec came out finalized over a month ago.  :-)

**Comment by debois** [comment]
I think we want to follow MDL. 

There's only so much time. MDL has resources and access to Google's Material team, so they are better placed to get the spec right. They also have way more JS/CSS and, especially, testing resource. I think we get farther by piggybacking on MDL.

That said, we could do a Material.Extras?

**Comment by debois** [comment]
... I think the relative date/time would be an ideal candidate for a Material.Extra. A PR would be awesome?

**Comment by OvermindDL1** [comment]
Heh, keep poking me about it and when I get time then I will pull it out of my project and clean it up.  :-)

And yes, mdl is following the Material spec, they are adding their missing parts at this time even, so if you are continue using their files then many of the above component suggestions will actually automatically appear, reltime is not one though, so definitely a good addition to Material.Extra.  :-)

**Comment by OvermindDL1** [comment]
Hmm, I've needed the arbitrary Dropdown component again, and I noticed others have looked for it too in `elm-mdl` https://www.dailydrip.com/blog/elm-pair-programming-josh-adams-and-luke-westby-pairing-on-colluder but not found it either.  Might be worth focusing on...

**Comment by debois** [comment]
Absolutely. I'd love that PR?

**Comment by OvermindDL1** [comment]
Hmm, a fairly complete Material library (although uses react) to perhaps test features from:  http://www.material-ui.com/#/components/app-bar

I notice their button ripples are multiplicitive, as in clicking a button rapidly causes multiple ripples to wave out, wonder how to the spec that is...

**Comment by OvermindDL1** [comment]
Another Material library for javascript too:  https://www.muicss.com/docs/v1/css-js/appbar

Not as complete, about on par to an older MDL, but might have ideas.

(Do note, I am mostly noting this down for my reference later to implement features.)

**Comment by OvermindDL1** [comment]
On an aside, the 'Dropdown' I refer to here is called 'Popover' by bootstrap, that might be a better name for a 'generic popup' container...

**Comment by OvermindDL1** [comment]
Hmm, http://mdbootstrap.com/components/buttons/ has a *ton* of components in the left hamburger menu that is a materialize bootstrap, lots of ideas here...

**Comment by OvermindDL1** [comment]
That latest link also has ripples that appear for each click instead of once.  It looks like all they do is add a "waves-effect" css (along with others to state how the waves act, there appear to be many styles), but all that does is react to onClick's and add a div with a styles that does the translation.  This would be very easy to do in an elm-mdl thing.  Could make it generic even.  Say you could make a new elm-mdl Attribute/Option for the ripple, something you could add to any component and tell it how to listen to the object it is defined on (say the "click" by default, or send your own messages to it?), and anytime it receives one it just adds an appropriate empty div to it that does the animation then vanishes after a short time.  Could end up making this an "elm-material" library, remove the dependency on mdl little by little...

**Comment by OvermindDL1** [comment]
Lot of great material things here, select boxes and more.

**Comment by OvermindDL1** [comment]
Yeah http://materializecss.com/ definitely has a *lot* more things than mdl, the css has better features, there are more components (many that work without JS), a lot of components added that are purely JS driven.  And most of it is very material'y...  Interesting...

**Comment by OvermindDL1** [comment]
An aside, materialize, although having more, is smaller than mdl, interesting...

**Comment by OvermindDL1** [comment]
The other big Officialish material library is for angular, very well made and more functional than MDL:  https://material.angularjs.org/latest/demo/autocomplete

However, MDLv2 looks to replace it as it is fully hookable into other frameworks (that have such javascript hooks).

**Comment by aforemny** [comment]
We are currently trying reorganize issues a bit and this issue did not make the list. It touches on too many rough edges in elm-mdl and we are trying to prioritize the easier fixes we can do right now. Please understand that I am closing this until we have things worked out on our ends (see #328).
