### ISSUE TITLE
Textfield line animation doesn't acknowledge padding

### ISSUE THREAD

**Issue by RobertWalter83** [debois/elm-mdl#148]
Maybe this is a non-issue.

I have a Textfield where I want to override the padding (default seems to be 20px).

```
[ Textfield.render Mdl
    [ 0 ]
    mdl
    [ Textfield.text'
    , Textfield.value model.value
    , css "padding" "10px"
    ]
```

When I set a cursor in the editable text line, the line gets animated using the default padding:

![image](https://cloud.githubusercontent.com/assets/5462981/17440590/8ea03d14-5b2d-11e6-9288-db4bfdc7f367.png)

Is the recommendation to never change a textfield's padding?

**Comment by OvermindDL1** [comment]
I've noticed that as well, the line appears 'inside' the textfield.  On scrollable multi-line ones the line appears over text when scrolled in most positions even without changing padding (well I might have some loose css somewhere doing that...).

**Comment by debois** [comment]
Use the `Textfield.style` option to style the underlying `input` field. Out in 7.2.0 just now; docs [here](http://package.elm-lang.org/packages/debois/elm-mdl/7.2.0/Material-Textfield#styling).
