### ISSUE TITLE
Travic CI and elm-test

### ISSUE THREAD

**Issue by hakonrossebo** [debois/elm-mdl#16]
To automate verification with multiple contributors, would it help if we set up Travis CI integration and some simple testing?

Travis CI is free for open source and hooks up to the Github repository.
[Travis CI](https://travis-ci.org/)

The readme on [elm-test](https://github.com/deadfoxygrandpa/elm-test) has a description on how to set up a .travis.yml file. I guess it could could work without tests in the beginning, just to ensure everything compiles when pushing to Github.

I don't think we need extensive testing, but with elm-test we could get faster feedback on development and also double as documentation on how to use elm-mdl components.

**Comment by debois** [comment]
That's a great idea! I think for starters, just ensuring everything compiles would be helpful. Do you know how to set this up, or should I look into it?

**Comment by hakonrossebo** [comment]
I can test this out on my fork and create a PR when it's working.

**Comment by debois** [comment]
Cool, please do.

**Comment by hakonrossebo** [comment]
#20

**Comment by hakonrossebo** [comment]
Regarding elm-test and testing. I've been getting this to work, but I'm not sure how/what to test. Ideally, for plain css testing, it would be great to have a way to verify that html created has the css/attributes expected. As I understand, Elm Html does not expose anything like this directly.

**Comment by debois** [comment]
I don’t have any good ideas here—most of the things you test for in Javascript are done by the Elm type-checker. Maybe leave at simply compiling for now?

**Comment by hakonrossebo** [comment]
Agree - we can use elm-test later if/when we need it.

-About the demo/examples

I've learned more about Elm/signals++/MDL the recent days. I've also been looking at the demo examples to get a feel for how to use this library. While the demo examples are great for demonstrating the capabilities, it is sometimes a bit hard to figure out/learn from the code in these examples. - Would it be useful if we also created a some simple tutorial/example pages? 
I was thinking something along with the existing examples - opening on a separate tab - i.e "Layouts" - A demonstration of a simple layout  (with a code/multiple code examples where devs could simply copy the code to get started with elm-mdl). The same for grid, buttons etc.

Maybe this could help getting more traction/use of elm-mdl. This could also be a separate repository/start kit.

I'm quite busy/unavailable during the next week, but I may get time to create some sample implementations. What do you think?

**Comment by debois** [comment]
More samples would be good.

I was hoping the Snackbar demo was more accessible, by the way—what do you think?

> On 31 Mar 2016, at 14:05, Håkon Rossebø <notifications@github.com> wrote:
> 
> Agree - we can use elm-test later if/when we need it.
> 
> -About the demo/examples
> 
> I've learned more about Elm/signals++/MDL the recent days. I've also been looking at the demo examples to get a feel for how to use this library. While the demo examples are great for demonstrating the capabilities, it is sometimes a bit hard to figure out/learn from the code in these examples. - Would it be useful if we also created a some simple tutorial/example pages?
> I was thinking something along with the existing examples - opening on a separate tab - i.e "Layouts" - A demonstration of a simple layout (with a code/multiple code examples where devs could simply copy the code to get started with elm-mdl). The same for grid, buttons etc.
> 
> Maybe this could help getting more traction/use of elm-mdl. This could also be a separate repository/start kit.
> 
> I'm quite busy/unavailable during the next week, but I may get time to create some sample implementations. What do you think?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/debois/elm-mdl/issues/16#issuecomment-203901349>

--

Søren Debois
IT University of Copenhagen
+45 5358 5818
