### ISSUE TITLE
Feature Request:  Menu optional disappear

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#163]
When clicking in menus that have, say, checkboxes, often we want to have the menu not disappear while they are choosing which things are checked, but we do still want it to disappear if they click outside of it.  Also we may have cases where we want it to disappear if the menu button is clicked or an item is clicked but not closed outside of it.  Or perhaps both, only have it disappear if the menu button itself is pressed again.

Thus, would it be possible to add a couple of menu options, something like `Menu.suppressOutsideClose` and `Menu.suppressInsideClose` for clicking outside of it auto-closing it and clicking on an item auto-closing it respectively (my naming is horrid I know).

**Comment by OvermindDL1** [comment]
Actually it would be nice for the insides if we could put the `Menu.suppressInsideClose` on the item options itself so that we can control which options will close or not close it?

**Comment by aforemny** [comment]
I would like to argue that check boxes inside menus are not supported by the [Material Design Specification](https://material.google.com/components/menus.html#menus-specs). Likewise, it is my understanding that menus should close on click. As I am not an expert on the spec, I might be wrong. In that case, please point it out to me.

However, even if the specification allowed that, another question would be if MDL has support for that as we are re-implementing that particular (itself incomplete) implementation of the spec.

**Comment by OvermindDL1** [comment]
I keep using that menu as an example because it is so simple to talk about.  I have a bigger one with a multi-select set of advanced options.  Admittedly a menu is not what I want, if you look back on https://github.com/debois/elm-mdl/issues/147 one of the suggestions was a generic 'Dropdown' that could have anything, that is actually what I am wanting, I am just working around it for now via using a menu.  Everything I listed in those suggestions is something that I would actively use 'now'.  :-)

**Comment by debois** [comment]
I'm closing this as the proposal seems a bit off spec. As usual, we'd consider a PR, of course.

**Comment by OvermindDL1** [comment]
Yeah the Material v2 Menu is quite a bit more powerful.  Once the spec is followed then the Menu will not only have functionality like this but more as well, so this seems subsumed by whenever the spec is followed.
