### ISSUE TITLE
Custom event handlers for components

### ISSUE THREAD

**Issue by vipentti** [debois/elm-mdl#164]
Hello there!

We had some discussion about custom event handlers in #130 and we added support for `Textfield.on` in 7.3.0. 

I'd like to open a discussion about possibly adding more general support for `on` and perhaps even `onWithOptions` for MDL components.

Enabling users to add custom event handlers does have a fair chance of breaking things with certain events such as `blur` and `focus` so this does need to be taken into consideration when it comes to enabling user defined events.

Another challenge is where to actually put the user provided event handlers in components. Some components are wrapped in `div` elements such as Textfield which allow us to put our internal event handlers on the container and the user provided ones on the internal `input` or `textarea`, and use the bubbling of certain events to our advantage. However, this is not the case with all the components. 

If there are any particular use cases for custom event handlers that are not currently possible it would be awesome to hear about them.

**Comment by debois** [comment]
If we could do this, it'd be great. I think the approach you took in #151 could reasonably be applied to other components. I think we need to understand and fix #166 before we proceed though. 

We might want to swap the approach of #151 and add user handlers to containers and our handlers directly on elements, that'll remove the problem of user handlers interfering. This'll generally mean that user's won't get keyboard events (right?). I'm unsure what's the right tradeoff no-keyboard, no-interference vs. keyboard, possible-interference.

I think the way to proceed would be to:
1. Fix #166.
2. Make a list of components that would benefit from arbitrary DOM handlers.
3. Go through the list, figure out which components have containers we can put user handlers on. 
4. Then decide what way to go.

?

**Comment by vipentti** [comment]
I think the possible implementation will change, depending on the number of components that could actually benefit from having arbitrary event handlers.

If only a limited number of components (in addition to `Textfield`) could even use them then it might not be worth it to try and create a generic solution. Instead just do something similar to the solution in `Textfield` per component. However, if most components could benefit and work with arbitrary event handlers then a generic solution might be preferable. 

I do think in the generic case *all* components will require internal changes to accomodate the event listeners because their internal DOM varies so much there is not a singular place to put the event handlers. 

Additionally, the placement of the user provided event handlers can vary depending on the implementation and particular events. Some events `bubble` properly meaning the internal handlers could be either on the outer containers or the inner elements.

One option would be to add *all* event handlers on the 'expected' element and then use event dispatching for the events that are possibly handled by us and users (e.g. `blur` and `focus`); such as in `Menu` or in the PR for the Firefox fix #173

**Comment by debois** [comment]
I like the "everything on the expected element" approach. 

Looking at #173, I think there _might_ be an opportunity for a generalised solution. For ease of discussion, let's forget about elm-mdl and `Options` for a moment, and pretend we're in plain `elm-lang/Html`. 

The key problem we're solving is dispatching more than one command for a single DOM event, [as seen in 173](https://github.com/vipentti/elm-mdl/blob/textfield-firefox-bug/src/Material/Textfield.elm#L302-L310). I think we could factor out those mechanics in a TEA module with no model component, something like this: 
```elm
module Dispatch exposing(Msg, Forward)

type Msg m = Forward (List m)

forward : Msg m -> Cmd m
forward (Forward msgs) = 
   List.map Helpers.cmd cmds |> Cmd.batch

on : (Msg m -> m) -> String -> List (Json.Decoder m) -> Attribute m
on fwd event decoders =
   case decoders of 
     [] -> Helpers.noAttr
     [x] -> Html.Event.on event (Json.Decode.map fwd x) 
     _ -> List.map (Json.Decode.map fwd) decoders |> Forward |> Html.Event.on event
```

One way to test this is idea is to implement such a module for real, find a good way to integrate it with `Options`, then refactor Textfield and Menu to use it (they'd obviously need container msg for the above `Msg m`.)

**Comment by OvermindDL1** [comment]
I use container messages in my Helpers module just for such similar things as well, it works well and I would recommend it (and was what I was hinting at when asking if there was a way to detect what an attribute is trying to listen for on an even so you could hook yours in).

**Comment by vipentti** [comment]
Hey,

@debois, Your suggestions is something like what I had in mind and started to experiment with. Before merging PR #173 I would like to try and see if I can work this out into a workable form. Even if initially we would only apply this method to `Textfield` it would allow us later to apply it to other components as well.


Thanks for all the feedback and suggestions!

**Comment by debois** [comment]
My pleasure :)

I like the plan of trying this out in #173.

**Comment by vipentti** [comment]
Implementing #179 has me curious on how many components could actually benefit from enabling custom event handling ?

`Button` could possibly benefit and then changing `Tooltip.attach` to use the Custom Event handlers would ensure that having a tooltip would not interfere with other elements. 

What saddens me slightly is that I believe this all could be avoided if Elm would allow one to actually have multiple Event listeners for an event like JavaScript does. One can call `element.addEventListener` and have multiple listeners being called in no specified order I believe.

**Comment by aforemny** [comment]
As far as I can tell this is resolved in current v8, so I will close here. Even though we are currently only using this on Textfield and I agree that using it on Buttons would make sense. Could you share your thoughts on #333? :)
