### ISSUE TITLE
Textfield has no class 'is-focused' in Firefox

### ISSUE THREAD

**Issue by Lesuk** [debois/elm-mdl#166]
![textfield-focus-firefox](https://cloud.githubusercontent.com/assets/2499776/17583889/17a58460-5fbc-11e6-837b-7390b1ec1020.gif)

**Comment by debois** [comment]
I can confirm this on Firefox/Mac OS.

**Comment by vipentti** [comment]
I'll look into this

**Comment by vipentti** [comment]
Found out the culprit. Just need to figure out a workaround.

Issue is that Firefox does not support `focusin` and `focusout` events that are currently being used by the containing div to capture focus. 

[Focusin](https://developer.mozilla.org/en-US/docs/Web/Events/focusin#Browser_compatibility) and [Focusout](https://developer.mozilla.org/en-US/docs/Web/Events/focusout#Browser_compatibility) as well as a reported [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=687787)
