### ISSUE TITLE
Unable to find a set of packages that with elm-mdl

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#168]
$ yes | elm-package install debois/elm-mdl
    $ To install debois/elm-mdl I would like to add the following
    dependency to elm-package.json:
    
        "debois/elm-mdl": "7.3.0 <= v < 8.0.0"

    May I add that to elm-package.json for you? (y/n) 

    Error: Unable to find a set of packages that will work with your constraints.

**Comment by debois** [comment]
You're on 0.17.1?

**Comment by aforemny** [comment]
I am not. Thanks! :)

**Comment by wintvelt** [comment]
Curious to know what solved your issue. I am running into the same error:
```
$ elm-package install debois/elm-mdl
To install debois/elm-mdl I would like to add the following
dependency to elm-package.json:

    "debois/elm-mdl": "7.6.0 <= v < 8.0.0"

May I add that to elm-package.json for you? (y/n) y


Error: Unable to find a set of packages that will work with your constraints.

Claires-Air:twapp wintvelt$ elm-package install debois/elm-mdl

Error: Unable to find a set of packages that will work with your constraints.

```
Where can I see what version of Elm I am running?

**Comment by jamesporter** [comment]
For anyone else encountering this check that your system version of elm is up to date (not just the project version).
