### ISSUE TITLE
Production Builds end up getting demo assets

### ISSUE THREAD

**Issue by knewter** [debois/elm-mdl#169]
I pulled in elm-mdl as a dependency in a Phoenix application via `elm-brunch` and the assets started to go into my build pipeline from the demo itself.  Super weird outcome, and it's a result of the demo coming down with the package itself.  Possible solutions:

- Package doesn't include the demo
- Demo moves to a different repo
- ?

**Comment by OvermindDL1** [comment]
For note, I use Phoenix and elm with elm-mdl and this does not happen.  Your /elm-stuff/ is not somewhere other than your project root directory is it?

**Comment by knewter** [comment]
I can confirm that this is likely a sad configuration problem in brunch,
nothing to see here, move along :)
