### ISSUE TITLE
Layout.navigation ignores styles

### ISSUE THREAD

**Issue by altaic** [debois/elm-mdl#170]
Not a big deal, but it'd be nice to be able to style `Layout.navigation` as implied by the type signature. Currently it simply ignores the styles passed in:

```elm
{-| Container for links.
-}
navigation : List (Style m) -> List (Html m) -> Html m
navigation styles contents =
  nav [class "mdl-navigation"] contents
```

I guess this is more about documentation. Trying to add styles leads to head-scratching, and, in my case, looking at `elm-mdl`'s source; for others it might instead lead to frustration.

**Comment by debois** [comment]
Thanks!
