### ISSUE TITLE
Typography module

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#18]
Material design defines [typography styles](https://www.google.com/design/spec/style/typography.html#typography-styles) in great detail. MDL apparently (but undocumentedly) [implements this](https://github.com/google/material-design-lite/blob/master/src/typography/_typography.scss#L123-L240). 

We should have the corresponding Styles in a Typography module with demo page etc.

**Comment by vipentti** [comment]
If no one else is currently working on this I can take it upon myself.

**Comment by debois** [comment]
Very good!
