### ISSUE TITLE
Menu's do not support cascade though it is in the spec.

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#182]
As per https://material.google.com/components/menus.html#menus-usage Menu's are supposed to be able to cascade, but having issues with that.  In addition Menu's are supposed to not only support icons, but any type of button, such as text or images.

This is also currently being fixed in upstream mdl so it should here too.

**Comment by debois** [comment]
Could you give a link to the upstream fix?

**Comment by OvermindDL1** [comment]
`Currently being fixed`:  https://github.com/google/material-design-lite/issues/4508

The authors of MDL have made an absolute *ton* of issues a little bit ago to get MDL up-to-spec with actual Material and they are slowly working through them.  When they are up-to-spec then they plan to release MDLv2  :-)

**Comment by debois** [comment]
Ok, closing this for now, we'll get back to it when we start looking seriously at v2z
