### ISSUE TITLE
Material Themes

### ISSUE THREAD

**Issue by OvermindDL1** [debois/elm-mdl#183]
Material apparently is supposed to handle a set of simple and interchangeable themes, and this support is being added to upstream mdl currently as well.  The spec defines it as https://material.google.com/style/color.html#color-text-background-colors where a set of configurable colors control how things are shaded, surface height, etc...  Including dark themes.  This should probably be added here sooner rather than later or it will make it more difficult to add it to the components later (especially as upstream mdl is recently currently in the process of adding a **LOT** of components so they follow the Material spec properly).

I am curious if it would be better for it to be css driven, or part of the mdl model...  Hmm...

**Comment by debois** [comment]
We support this to the extent upstream does, through `Material.Theme`.

**Comment by debois** [comment]
We support this to the extent upstream does, through `Material.Theme`.  

It's likely be very hard to extend on upstream ourselves without having to load custom CSS. We had that discussion in the past, and decided we _really_ want upstream CSS. (Although there were good arguments in the other directions.)

Closing this; as always, a PR would be very welcome.
