### ISSUE TITLE
Issues on Windows and Chrome 53.0.2785.57 beta-m (64-bit)

### ISSUE THREAD

**Issue by vipentti** [debois/elm-mdl#184]
Not quite sure what is going on but on Chrome on Windows 10 Menus are positioned in a strange way 
![menu_chrome_bug](https://cloud.githubusercontent.com/assets/4726680/17695841/23c25e4e-63b3-11e6-813b-9bc91d9dc08b.gif)

**Comment by vipentti** [comment]
Found another issue that is present in elm-mdl and this particular version of Chrome. Where tooltips appear blurry. This does not occur in regular MDL.

![tooltip_chrome_bug](https://cloud.githubusercontent.com/assets/4726680/17699716/fa902af2-63ca-11e6-89d4-4d77b5eee13e.gif)

**Comment by vipentti** [comment]
Found culprit to the tooltip. For some reason having `will-change: transform` in the `.mdl-tooltip` class does not work properly on this version of Chrome.

**Comment by debois** [comment]
Is this an instance of #143?

Otherwise, maybe more debois/elm-dom#4 — we could try logging Menu.model during update, see if it gets positing right.

**Comment by vipentti** [comment]
I think it might be indeed the same as #143

**Comment by OvermindDL1** [comment]
What version of Chrome?  I have `Version 52.0.2743.116 m` on Windows 10 currently and not seeing the issue.  What is the DOM of the whole menu setup that you see?

**Comment by vipentti** [comment]
Chrome 53.0.2785.57 beta-m (64-bit)

**Comment by OvermindDL1** [comment]
So it really is just the beta version, hopefully fixed prior to release then?

**Comment by pdamoc** [comment]
I'm using `Version 53.0.2785.89 (64-bit)` and the blur issue is still present.
