### ISSUE TITLE
Feature collaboration

### ISSUE THREAD

**Issue by hakonrossebo** [debois/elm-mdl#2]
Could I suggest that you create separate issues for each of the features you want contributions on? Then contributors could avoid working on the same issue?

It is also possible to use [waffle.io](https://waffle.io) (free for open source)  as a simple Kanban board.

**Comment by debois** [comment]
I think it's a good idea to clearly mark out what's being worked on, but maybe having it spread out over an Issue could be confusing. 

Perhaps we could use this Issue to declare interest, then I can make a note of work-in-progress in the list of components in the main README.

I can start: I'm halfway through the snackbar.

Is there anything you'd like to work on?
Perhaps I should just mark in the main README the components being worked on? The people could

**Comment by hakonrossebo** [comment]
Seems like a good solution. What do you think would be the simplest/least friction item to start on? Badges looks minimal.

**Comment by debois** [comment]
I think you're right, Badges is probably the minimal starting point. If you feel slightly more adventurous, Cards are probably not significantly more complex, but might contain an interesting question about what's the right Elm API for them. Possibly the same for lists. 

Do you want me to sign you up for one of these on the main page?

**Comment by hakonrossebo** [comment]
I probably need a little time to get started, but sign me up for Badges. Do you just use Demo.elm to test/verify features?

**Comment by debois** [comment]
> I probably need a little time to get started, but sign me up for Badges.
> 
Great! Will do.
> Do you just use Demo.elm to test/verify features?
> 

Yes; it doubles as testbed and public demo—at some point the Demo should maybe become a separate repository.  For now, if you could  add another tab for Badges, that’d be great!

**Comment by debois** [comment]
Hi Håkon, are you still interested in adding cards or some examples?

**Comment by hakonrossebo** [comment]
Hi, I'm just back from a holiday/training camp and just getting up to speed. Great to see many updates the last week. Yes, still interested in adding cards or examples - but please re-assign if you or anyone else wants to grab the issues first.

**Comment by debois** [comment]
Welcome back :)

If you could do Cards, that’d be great!

**Comment by debois** [comment]
Hi Håkon, 

[Mike Onslow](https://github.com/mikeonslow) wants do Cards, so I'm transferring this over to him. Hope you don't mind!

If you want to do something else (Lists are still open?), do let me know!

Cheers,

Søren

**Comment by hakonrossebo** [comment]
That is fine. I've been busy for a while but hope to get back in the loop soon.

**Comment by debois** [comment]
Ok—looking forward to having you back!
