### ISSUE TITLE
Add support for Id attribute

### ISSUE THREAD

**Issue by vipentti** [debois/elm-mdl#204]
With the new [elm-lang/Dom](http://package.elm-lang.org/packages/elm-lang/dom/1.1.0/) package users can focus and blur elements based on the Id. 

For some use cases the following works
```elm
Options.attribute <| Html.Attributes.id "my-id"

-- For example with Textfield 
-- NOTE: Setting the attribute on style to set it to the actual input and not the container

, Textfield.style [ Options.attribute <| Html.Attributes.id "my-id" ]
```

But `Options.attribute` is restrictive for a reason as discussed in #192 . So adding `Options.id` might be a good idea. However, this has a problem that setting the id on a `elm-mdl` component might not result in what users might expect. 

For example settings `Options.id` on a textfield the expected result would be to have it affect the actual `input` and not the container, because to focus the textfield you need to set focus on the `input` and not the container. Similar problems might occur in other components where the component has several parts inside a container. 

This should be taken into consideration on how to best handle this particular matter. 

**NOTE** The problem would still exist, even if we made `Options.attribute` less restrictive.

**Comment by OvermindDL1** [comment]
```elm
-- In options
type Id object_type
  = Id String
  = IdOn object_type

-- In, say Textfield
type TextfieldId
  = OuterDivId String
  | LabelId String
  | TextfieldId String

id : String -> Options.Id TextfieldId
id id = Options.Id id

idOn : TextfieldId -> Option.Id TextfieldId
idOn on = Option.IdOn on

-- Used like:
    , Textfield.render Mdl [2] model.mdl
        [ Textfield.label "Floating label"
        , Textfield.idOn (Textfield.OuterDivId "some-id")
        , Textfield.idOn (Textfield.LabelId "another-id")
        , Textfield.id "id-on-default-thing"
        , Textfield.floatingLabel
        , Textfield.text'
        ]
```
Or something like that (entirely untested code just typed in-github as an idea).

**Comment by debois** [comment]
Agree, we should have this: it's reasonable to expect, now that the DOM API is based on Ids, that Ids will sneak their way into other elm APIs.

Assuming that what we can do with Ids is the current scroll, focus and getBoundingClientRect, I tried to figure out for which current component which ids users might need: 

- Button. Container (position). 
- Badge. No id. 
- Cards. Container (position). 
- Dialog. No id. 
- Footers. [Don't know. @vipentti?]
- Grid. Top-level container (position), cell container (scroll).
- Layout. No id. 
- List. Container (position). 
- Loading. Container (position).
- Menus. [Don't know. @aforemny?]
- Slider. Container (position)
- Snackbar. No id. 
- Tables. Container (position).
- Tabs. Container (position). Contents (scroll). 
- Textfield. Container (position). Input (focus). 
- Toggles. Container (position). Input (focus). 
- Tooltips. No id. 
- Typography. No id. 

If you agree with this list, then: 
- 6 components need no Id
- 6 components need Id on container only
- 3 (4*) components need Id on container and key element

(*) 4 if you count Grid cells, but you can think of Cells as top-level containers in their own right—in particular, they aren't styled by the top-level constructor. 

I think I'm in favour of keeping the current approach from Textfield, where a special Option for the main `render` assigns options to the key element: that seems to cover all the cases here. (except if there's anything special with Menu or Footer). I'd like a better name for the inner styling option than `style`, though. 

Note that with this approach, we can do not only ids but also CSS, classes and events (note that the present discussion may also be relevant for #164 / #179).

**Comment by vipentti** [comment]
I think the `Textfield.style` type of option for "inner" attributes is okay. We should try and come up with a more descriptive name though. 

I assume we will have a global `Options.id` and then this can be assigned both to the main `render` options as well as the `innerOptions` for those components that provide that option ?
