### ISSUE TITLE
Hide header when scrolling main content

### ISSUE THREAD

**Issue by pinx** [debois/elm-mdl#21]
The Whatsapp messenger has this behavior. When you scroll down (swipe up), the header title (not the tabs) starts to disappear. I tried binding [elm-scroll](https://github.com/abrykajlo/elm-scroll), but it's not that simple.

**Comment by debois** [comment]
Have you tried setting the [Mode of the header](http://package.elm-lang.org/packages/debois/elm-mdl/1.0.1/Material-Layout#Mode) to "scroll"?

**Comment by debois** [comment]
Is what you need the [Waterfall header](https://www.getmdl.io/components/index.html#layout-section/layout) (scroll down a bit) of MDL?

**Comment by pinx** [comment]
Yes, I think so. Is it possible to use it from elm-mdl, or do we need to make code changes for this?

**Comment by pinx** [comment]
I noticed you have commented out Waterfall Mode. Issues? Anything I can help with?

**Comment by debois** [comment]
I didn't know initially how to read the scroll position of the main contents, which the Waterfall Mode needs. I do now, though. If you're interested in adding this, that'd be great! What you'd need to do is re-implement these  bits of logic from the MDL implementation: 

 - Add an `on "scroll"` handler to 
[ `main'` in Material.layout](https://github.com/debois/elm-mdl/blob/master/src/Material/Layout.elm#L418).

- When handling that event, you need to fetch scrollTop from the event (you could use the decoder `(DOM.target DOM.offsetTop)` from my [DOM package](http://package.elm-lang.org/packages/debois/elm-dom/1.0.0/DOM#scrollTop)). 

- Duplicate [this bit of logic](https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L136-L160) from the MDL implementation. (Working out what goes on here is the time-consuming bit.)

- [Install handlers for  "click" and "transitionend"](https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L341-L347) on the [header](https://github.com/debois/elm-mdl/blob/master/src/Material/Layout.elm#L308-L311).

Is this something you'd be willing to take on?

**Comment by pinx** [comment]
I'm pretty new to Elm, so it won't be easy, but I'm willing to learn. Thanks for the tips, I'll get started, soon. Can we continue the discussion in email?

**Comment by debois** [comment]
Great! Can you contact me at debois.junk@gmail.com?

> On 30 Mar 2016, at 07:45, Marcel van Pinxteren <notifications@github.com> wrote:
> 
> I'm pretty new to Elm, so it won't be easy, but I'm willing to learn. Thanks for the tips, I'll get started, soon. Can we continue the discussion in email?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/debois/elm-mdl/issues/21#issuecomment-203257914>

--

Søren Debois
IT University of Copenhagen
+45 5358 5818

**Comment by debois** [comment]
I didn't hear from you yet, I think. Did I miss your email?
