### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by pyladune** [debois/elm-mdl#214]
Not sure it is the right place to mention, but the users link on hex packages for mdl is not working. This is a great idea and would be useful if working.

http://package.elm-lang.org/packages/debois/elm-mdl/7.5.0
-> "Check out the users page for a list of projects using elm-mdl."

here is the error message : problem with parameter 'version': Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)

**Comment by hakonrossebo** [comment]
The immediate solution for you is to check this working link: https://github.com/debois/elm-mdl/blob/v7/USERS.md. We just need to fix the link used by the package documentation.

**Comment by hakonrossebo** [comment]
@debois - how is this working - is the text beeing copied from the README on release?

**Comment by debois** [comment]
I think the package repo loads the contents of the tag (7.5.0) from github and uses the README.md as the front page. We can probably just fix the link directly in the README—its relative, which is probably why elm package don't like it. Maybe file an issue against elm package also?

**Comment by hakonrossebo** [comment]
I've submitted PR #228, and also created an issue on elm-package here https://github.com/elm-lang/elm-package/issues/238

**Comment by debois** [comment]
Closed in #228.
