### ISSUE TITLE
Elements in lists not getting rendered

### ISSUE THREAD

**Issue by z5h** [debois/elm-mdl#224]
It seems if `li` are rendered with a `body` that body is not rendered if the content contains something other than text.

In the example there are 2 `li`s. One has a textfield as it's content, and the other has plain text. Only the one with plain text has it's body shown.  

I see in [Google's spec](https://material.google.com/components/lists.html#) that no lists ever contain anything other than text. If that is the cast, perhaps elm-mdl needs to enforce this with types. 
 
![image](https://cloud.githubusercontent.com/assets/81692/18255921/ad9b2730-737c-11e6-820f-c56f72a60eba.png)

```Elm
import Html.App as App
import Html exposing (..)
import Material
import Material.List as Lists
import Material.Scheme
import Material.Textfield as Textfield

type alias Model = { mdl : Material.Model }


model : Model 
model = { mdl = Material.model }

type Msg = Mdl (Material.Msg Msg)
      
update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
  case msg of
    Mdl msg' -> 
      Material.update msg' model

type alias Mdl = 
  Material.Model 

view : Model -> Html Msg
view model =
  Lists.ul []
    [ Lists.li [Lists.withBody]
        [ Lists.content []
            [ Textfield.render Mdl [1] model.mdl 
                [ Textfield.label "label"
                , Textfield.value "Where's my body?"
                ]
            , Lists.body [] [text "you can't see me"]
            ]
        ]
    , Lists.li [Lists.withBody]
        [ Lists.content []
            [ text "I have a body"
            , Lists.body [] [text "you can see me"]
            ]
        ]
    ]
  |> Material.Scheme.top
  
main : Program Never
main =
  App.program 
    { init = ( model, Cmd.none ) 
    , view = view
    , subscriptions = always Sub.none 
    , update = update
    }
```

**Comment by debois** [comment]
As you mention, lists in the spec seem to be intended only for text, so you may want to consider if `Material.Lists` is what you want here—maybe just do a plain `Html.ul` instead of `List.ul` and manually apply the styling you need?

Technically, the reason you don't see the "you can't see me" text is because `List.li` have fixed height and `overflow: hidden`. The textfield leaves no space for the body text. 

Hope this helps. Very nice and helpful small example, btw :)
