### ISSUE TITLE
Grid: setting size/offset to 0 produces size/offset of 1

### ISSUE THREAD

**Issue by ydNoam** [debois/elm-mdl#241]
The bug is easy to reproduce:

``` elm
Grid.offset Grid.Phone 0 == Grid.offset Grid.Phone 1 -- True
```

Of course you could simply remove `Grid.offset Grid.Phone 0`, but I believe there's no reason to disallow the value `0`, certainly when Elm's type system cannot verify that you used a positive integer.

Also, there might be an occasion where you'd like to variably offset a cell, and

``` elm
\x -> Grid.offset Grid.Phone x
```

will cause mentioned bug when applied to `0`.

**Comment by debois** [comment]
Thanks, nicely spotted.
