### ISSUE TITLE
Fixed drawer below header

### ISSUE THREAD

**Issue by migore** [debois/elm-mdl#243]
I'm trying to make a design with the header starting in the beginning with a fixed drawer below the header, like the following:

<img width="706" alt="screen_shot_2016-10-07_at_9_25_57_pm" src="https://cloud.githubusercontent.com/assets/301176/19208754/fada2c78-8cd4-11e6-82a9-3615f41f06c5.png">

Instead of this:

<img width="449" alt="screen_shot_2016-10-07_at_9_31_04_pm" src="https://cloud.githubusercontent.com/assets/301176/19208811/84957fee-8cd5-11e6-9948-df00feb40e45.png">

But I didn't find a way to overwrite the header `margin-left` (and fix the width as well) when creating the header (the tag is created automatically), I just pass the contents to it when creating my layout. Is there any way to do it?

The workaround would be to write some CSS.

**Comment by migore** [comment]
I did some further investigation on the page and the page mentioned with the menu below the header adds the menu in the body, and not as a drawer.

So in the elm-mdl I would pass 

```elm
{
...
, drawer = []
}
```

and create the side menu manually.

Closing this issue.

**Comment by SkyCodeTechnology** [comment]
Can you provide code example? Thank you!

**Comment by migore** [comment]
Sorry, I ended up not using it and discarded it. :(
