### ISSUE TITLE
The drawer menu icon is not vertically centered

### ISSUE THREAD

**Issue by ydNoam** [debois/elm-mdl#244]
A picture is worth a thousand words.

![elm-mdl drawer menu icon](https://cloud.githubusercontent.com/assets/20953786/19273138/124431b8-8fd4-11e6-8087-5aaf55cacb37.png)

Another thousand words:

![google's inbox drawer menu icon](https://cloud.githubusercontent.com/assets/20953786/19273146/1822af74-8fd4-11e6-9ffc-feeda9607e29.png)

_Chrome Version 53.0.2785.143 (64-bit) on macOS Sierra 10.12._

**Comment by debois** [comment]
This is a regression in upstream which was fixed in google/material-design-lite@f08ce0da0c8c0fafd21573c7ea9a11b5d9906487.
