### ISSUE TITLE
Using elm-mdl with components in other material libraries

### ISSUE THREAD

**Issue by simax** [debois/elm-mdl#248]
I'm new to elm and I was just wondering if it would be even possible to use elm-mdl in conjunction with something like [http://www.material-ui.com/#/components/date-picker](http://www.material-ui.com/#/components/date-picker). 

I need a datepicker component and the aforementioned library has one that fits the bill nicely and of course it has the "material" look and feel.  

I realise a datepicker is on the wishlist #147, but in the meantime, would it possible to use the datepicker component in the material-ui library using ports or whatever in the same project with elm-mdl or is that a dumb idea?

**Comment by OvermindDL1** [comment]
Hmm, theoretically possible but you'd need to send a port command to tell that library to initialize that element (and be sure to send a port command to disable it at least a frame before it is removed too, or make a native elm module and use the virtual-dom custom node, where you can do that yourself as I recall).

**Comment by simax** [comment]
OK, thanks. I suspect this may be beyond my current skill level with elm - as I said, I'm a noob here. 

Do you know if there's any timeline for having widgets like datepicker etc? Or even if they're actively being developed.

**Comment by OvermindDL1** [comment]
No one is working on one yet, but as I recall there is a pretty good datepicker in elm in another library already, it is not very material-looking, but it works.  It might be possible to materialize it.  Or if the license allows it, to absorb it and materialize it properly if you want to PR it?

And nah, that kind of port work is simple, just have to be careful with timing.  :-)

**Comment by simax** [comment]
Yes, I've seen some of the datepickers there's this [https://github.com/terezka/elm-datepicker](https://github.com/terezka/elm-datepicker) and this [http://package.elm-lang.org/packages/Bogdanp/elm-datepicker/3.0.1](http://package.elm-lang.org/packages/Bogdanp/elm-datepicker/3.0.1) but as you say, not material looking which is what I was after. 

I may try to use ports with [http://www.material-ui.com/#/components/date-picker](http://www.material-ui.com/#/components/date-picker) and see how it goes.

Thanks for the advice.

**Comment by debois** [comment]
I'd love a PR for this :)
