### ISSUE TITLE
Textfield.floatingLabel not working

### ISSUE THREAD

**Issue by jackalcooper** [debois/elm-mdl#249]
![image](https://cloud.githubusercontent.com/assets/5133557/19958612/9cb4e798-a1db-11e6-8e98-d569cddba700.png)

**Comment by jackalcooper** [comment]
```elm
Textfield.render Mdl
            [ 1 ]
            model.mdl
            [ Textfield.label "Floating label"
            , Textfield.floatingLabel
            , Textfield.text'
            ]
```

**Comment by jackalcooper** [comment]
Stupid me. I didn't use the model including Boilerplate Elm MDL model

**Comment by OvermindDL1** [comment]
> Stupid me. I didn't use the model including Boilerplate Elm MDL model

Would be nice if that could be automated yeah, perhaps webcomponents soon?  :-)

**Comment by jackalcooper** [comment]
Well I think it would be nice enough notice if there is an error message

**Comment by OvermindDL1** [comment]
> Well I think it would be nice enough if there is an error message

As I recall that is an Elm limitation.  So unless this project ports to a better language like Bucklescript or so, not easily possible yet.  :-)
