### ISSUE TITLE
Textfield.value does not update for empty string

### ISSUE THREAD

**Issue by Damukles** [debois/elm-mdl#261]
With my upgrade to elm-mdl 8.0 my Textfield.value does not display en empty string, when set in model:

`Textfield.value <| Debug.log "current" model.currentInput`

The Debug Log says "", but the last value persists in the input field.

**Comment by debois** [comment]
I'll look at this tomorrow morning; if you're in a hurry, a workaround could be to try using `Option.input` to set `Html.Attributes.value` to what you want directly.

**Comment by debois** [comment]
I can't reproduce this, or maybe I don't understand the issue. Is this related to #264?
