### ISSUE TITLE
What are the advantages of uisng elm-mdl VS Mdl CSS ?

### ISSUE THREAD

**Issue by pyladune** [debois/elm-mdl#268]
Sorry for this trivial and newbies question.
I have played both with elm mdl and mdl directly by using core mdl css. Both works fine, 

I am not sure to see the advantages of using elm-mdl. Despite i guess there are more pro than cons !

Thanks

**Comment by debois** [comment]
If you're using any part of MDL that requires Javascript (ripples on buttons, toggles, etc,; layout) then the MDL css won't be enough. Elm-mdl re-implements the missing javascript bits in elm.
