### ISSUE TITLE
Links in Material module documentation to examples are broken

### ISSUE THREAD

**Issue by emmanuelrosa** [debois/elm-mdl#269]
When the examples were renamed in commit [7b455a54367394cd30833a91c0733827cb4523ad](https://github.com/debois/elm-mdl/commit/7b455a54367394cd30833a91c0733827cb4523ad#diff-44d58172f3b0e9bbf7e294d666958bfe) The links in the Material module documentation (_Shorthands for TEA components section_) broke. 

For instance, the link to a plain TEA example incorrectly points to https://github.com/debois/elm-mdl/blob/master/examples/Component-TEA.elm.

**Comment by debois** [comment]
Ah. @hakonrossebo do you have time to take a look?
