### ISSUE TITLE
Material.Component not exposed

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#272]
Is the module supposed to be exposed? That would solve a problem that recently came up [on reddit](https://www.reddit.com/r/elm/comments/5ml7y9/how_do_i_call_a_recursive_update_in_elm_018_in/), ie. how to lift `Layout.ToggleDrawer` to `Material.Msg`.

**Comment by debois** [comment]
I'm not sure; I don't think it's something we want users to access (I'm still considering moving all the messages into one big file and be done with it.)

For the guys particular problem, can't he just use `Material.Layout.toggleDrawer`?

**Comment by debois** [comment]
Closing this for now; re-open if `Material.Layout.toggleDrawer` isn't enough.
