### ISSUE TITLE
Textfield with dropdown component (PR #273)

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#282]
[Demo](http://aforemny.github.io/elm-mdl/#select), [code](https://github.com/aforemny/elm-mdl/tree/component-select).

This issue is a continuation of PR #273, until I rebase against elm-debois/msg.

**Comment by tranhoangvuit** [comment]
Can we use it for multiple language for website ?

**Comment by martindlarsson** [comment]
Can you add a flag/option to disable text input? Just like an ordinary drop down menu? As it is now it gets annoying on mobile when the keyboard pops up every time you touch the select. And in my application I don't want the user to type anything but the given options.

**Comment by aforemny** [comment]
I agree. Because of that example, the component should be modeled around a button + menu rather than input + menu. Would that solve the problem for you?

**Comment by martindlarsson** [comment]
Yes it would! Thanks

**Comment by 4ZM** [comment]
What is the status of this? I would really like to use this component from the main mdl library.

**Comment by dennissivia** [comment]
I am wondering about the status as well. not sure if I have to switch to the fork in order to use them or if there is currently work being done. Would be great to hear the latest status.

**Comment by aforemny** [comment]
Merged to branch new-v8.

**Comment by zzantares** [comment]
@aforemny where exactly is the merge? I'm trying to use this in `8.1.0` but `Material.Select` does not exist.

**Comment by OvermindDL1** [comment]
@ZzAntares Literally to where he said, the `new-v8` branch (in git), you need to use the git new-v8 for now until it is published.  :-)

**Comment by Socratic1** [comment]
I'm having an issue that the arrow for the select dropdown appears on the left, not on the right. Have others encountered this?

**Comment by aforemny** [comment]
@Socratic1 Seems to be broken in [current wip demo](http://debois.github.io/elm-mdl/wip.html#select), too. I will check the CSS and report back shortly.

**Comment by aforemny** [comment]
@Socratic1 I updated the [wip demo](http://debois.github.io/elm-mdl/wip.html#select). Please note that you will have to include [select.css](https://github.com/debois/elm-mdl/blob/v9/styles/select.css) as in [wip.html](https://github.com/debois/elm-mdl/blob/gh-pages/wip.html#L40).

**Comment by dennissivia** [comment]
Should this issue be reopened, since it seems to superseed #79 and the actual features is not merged/done yet? Or is there another (open) issue or is this no longer supposed to be open because a PR exists?

**Comment by aforemny** [comment]
My focus shifted to https://github.com/aforemny/elm-mdc. Apologies.
