### ISSUE TITLE
Layout Doc boilerplate doesn't match Material module boilerplate example

### ISSUE THREAD

**Issue by benjamin-bergia** [debois/elm-mdl#285]
In the `Material` module documentation, the `Msg` type is defined as 
```
type Msg =
  ...
  | Mdl (Material.Msg Msg)
```
In the Layout documentation, it is:
```
type Msg =
  ...
  | Mdl Material.Msg
```

I wonder if it would be easier to define the boilerplate into the `Material` module and just link to it when needed.

**Comment by aforemny** [comment]
I corrected it in 6840fb4814256fad4d50a0ae5ed4589ba15661b8. Thanks!

I did not refactor the documentation as we want to emphasize subscriptions when necessary.
