### ISSUE TITLE
Add "number" type function for Textfield

### ISSUE THREAD

**Issue by Janiczek** [debois/elm-mdl#286]
In similar vein as Textfield.email or Textfield.password
Is tis a good idea, or is there some other canonical way? (regexes and validation?)

**Comment by andys8** [comment]
Missing the ability to set the type of the input, too. "date" and "time" would be great!

**Comment by FabienHenon** [comment]
And "tel"

Is there a workaround for this?
Because I'm about to fork the project for this feature :(

**Comment by Edward-Lombe** [comment]
Can say that I would love an ability to set the type of an input to date.

Currently, I'm trying to get the following code to work, but it has no effect for some reason

```elm
Textfield.render Mdl
        [0]
        model.mdl
        [ Textfield.label "Date input"
        , Textfield.floatingLabel
        , Options.onInput SetDate
        , Options.input <| [ Options.attribute <| Html.Attributes.type_ "date" ]
        ]
        []
```

But the type resolutely stays as text.

**Comment by aforemny** [comment]
This will only come in v9. I will close here and track progress in #335.
