### ISSUE TITLE
Grid Hide

### ISSUE THREAD

**Issue by uptoit** [debois/elm-mdl#287]
when hiding a class:

`<div class="mdl-cell--hide--phone mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell">`

should be:

`<div class="mdl-cell--hide-phone mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell">`

Grid.elm line 220 should be
 ` "mdl-cell--hide" ++ suffix device`
not
 ` "mdl-cell--hide-" ++ suffix device`

BTW what an awesome piece of software

**Comment by aforemny** [comment]
This is fixed in new-v8 (ba70b608a402847792fcd6f9f973cb388aef7f82). Thanks!
