### ISSUE TITLE
Button.link with wrong example in package documentation

### ISSUE THREAD

**Issue by alehostert** [debois/elm-mdl#293]
Hello.

The example in [Button.link documentation](http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Button#link) don't work:

```
Button.render Mdl [0] model.mdl
  [ Button.link
  , Options.attribute <|
      Html.Attributes.href "#some-url"
  ]
  [ text "Link Button" ]
```

But, the example in [Demo Button Page]() works:

```
Button.render Mdl [9, 0, 0, 1] model.mdl
  [ Button.ripple
  , Button.colored
  , Button.raised
  , Button.link "#grid"
  ]
  [ text "Link" ]
```

The issue is just to fix the example on documentation, adding the `String` argument `Button.link` is expecting.

**Comment by aforemny** [comment]
This is fixed in new-v8 (05429195be7cb73ad38dcc94326473a73af4c987). Thanks!
