### ISSUE TITLE
Data from Textfield is bleeding into another page's Textfield with a different index

### ISSUE THREAD

**Issue by tuxagon** [debois/elm-mdl#296]
Currently, I have a stepped form, where some inputs are on different views/pages. When a user completes one page, it will transition to the next. For an example setup, you can see https://github.com/mdgriffith/elm-style-animation/blob/master/examples/TurnPage.elm

The code I am using to render the textfield is 
```
textField : Material.Model -> String -> List Int -> Html Msg
textField mdl labelText index =
    Textfield.render Mdl
        index
        mdl
        [ Textfield.label labelText
        , Textfield.floatingLabel
        , Textfield.text_
        ]
        []
```
with an example usage
```
div []
    [ textField model.mdl "First Name" [ model.current, 0 ]
    , textField model.mdl "Last Name" [ model.current, 1 ]
    ]
```

`model.current` would be the same number in this example, but the text that is being populated in the "First Name" field is from a field that would have the index array of `[ model.current - 1, 0 ]`. I checked to see if the second number would matter at all and it does not (in regards to whether it would load text from a specific field on the previous view/page). In addition, it still happens if I explicitly set the index on every single field I have; it happens regardless of index.

Lastly, I have tried to use `Textfield.value ""` to force the value in the textfield to possibly be overwritten when it renders, but something is overriding even that. Nothing I have tried has worked and my initial inspection into the code didn't provide any immediate red flags.

**Comment by aforemny** [comment]
We are currently re-organizing issues and while I would like to look at this, I figure it is too old already. So please re-open if you are still interested in this as I would need some assistance running TurnPage.elm.
