### ISSUE TITLE
Options.onBlur event on Textfield

### ISSUE THREAD

**Issue by gergely-marko** [debois/elm-mdl#297]
If I subscribe to the onBlur event of a Textfield with my own Msg, then the animated style change is not carried out. Seems like the textfield does not receive the event. Same issue with onFocus.
You can see the issue on the elm-mdl demo page too, in "Textfields" tab, "Working with focus" section.

**Comment by OvermindDL1** [comment]
That is because the events need to be combined, elm does not have a trivial method to do that so it has to be special cased in the library for every one.

I am curious though, the animated style change can be done entirely within CSS with no JS or anything (my own projects are very materialy with no JS), perhaps that should be done?

**Comment by gergely-marko** [comment]
http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Options

At the end of the page, in "Multiple dispatch" section:

"The render function does all this automatically. If you are calling render, you do not need this property."

Am I misunderstanding something?

**Comment by bredikhin** [comment]
Getting something similar here: `onBlur` on a textfield doesn't remove the `is-focused` class. The event gets received though, but I end up having multiple `is-focused` textfields.

**Comment by gergely-marko** [comment]
I found a workaround via using Options.dispatch, just like the example in the docs.
Now I can handle my own onBlur, and mdl can handle their.

**Comment by cmditch** [comment]
@gergely-marko Do you have gist where you might show your solution of the textfield view in question, the update msg's involved, and any types as well? I'm trying to do the same thing, but it's not so obvious :-\  Thanks!

**Comment by gergely-marko** [comment]
@cmditch Look at this:
https://gist.github.com/gergely-marko/3fdd7dc39d42c8db8f30ed1d610e533c

This small user control is just a wrapper around an Inputfield. It validates and formats an Int to a specific "section" format. It is for displaying km values of road sections.
e.g. 2456 -> 2+456 (== 2 km 456 m)

**Comment by MazeChaZer** [comment]
FIY, there is an SCCEE in #319

**Comment by aforemny** [comment]
I will close here. Continuation (and fix) in #333. Thanks for all the input on this!
