### ISSUE TITLE
Button sizing issue

### ISSUE THREAD

**Issue by dillonkearns** [debois/elm-mdl#302]
Buttons are sized differently when link is present or not.

https://ellie-app.com/SFH8BR9CsGa1/1

![image](https://cloud.githubusercontent.com/assets/1384166/24881873/2d5881a8-1e0d-11e7-862b-bf11349bdcd9.png)

**Comment by vipentti** [comment]
This one seems to be due to the mdl css itself.

Also present in regular mdl here: https://codepen.io/anon/pen/QvwLzd

**Comment by dillonkearns** [comment]
Thanks for the response @vipentti. One possibility would be to always use anchor tags instead of switching between `button` and `a` based on whether there is a link present.

Or users could work around it using `Button.link "#"`, but if there are details in the URL already this workaround doesn't work without recreating or checking the current url.

Any thoughts?

**Comment by dillonkearns** [comment]
Here's an example of using `<a>` tags when there is no link present:
http://codepen.io/dillonkearns/pen/BRmWKy

**Comment by aforemny** [comment]
It seems like `buttons` set `box-sizing: border-box` by default. I added that as inline-css to set it on anchors. (abc1fc64d4f73c81b079fb31d21f7412a8f2bdf2) Thanks for the input!
