### ISSUE TITLE
Button disabled not working with link

### ISSUE THREAD

**Issue by dillonkearns** [debois/elm-mdl#303]
Buttons are not disabled when `Button.link` property added

https://ellie-app.com/SFH8BR9CsGa1/2

![image](https://cloud.githubusercontent.com/assets/1384166/24882107/eb5bfaf4-1e0d-11e7-8c1e-6366d23a7207.png)

**Comment by aforemny** [comment]
This is fixed in new-v8 (05429195be7cb73ad38dcc94326473a73af4c987). Thanks!
