### ISSUE TITLE
Header seems to pass under the tabs when disabled

### ISSUE THREAD

**Issue by benjamin-bergia** [debois/elm-mdl#304]
I don't know if it is an expected behavior but it looks kind of odd, here are some screenshots:
[With Header](http://i.imgur.com/mCG8cKb.png)
[Without Header](http://i.imgur.com/CLvak5A.png)
You can see a stripe of the same color than the header under the Tabs. It is more obvious when looking at the selected tab.

**Comment by aforemny** [comment]
I improved the situation in new-v8 (e95b0aa1da1949b3878524245f0ed3cc21511dde). It should work when you do not have a drawer (as in your configuration). I don't see an obvious solution in the case when you do have a drawer. Thanks! :)
