### ISSUE TITLE
Ripple buttons break Invisible Google reCaptcha

### ISSUE THREAD

**Issue by zgohr** [debois/elm-mdl#306]
[Ellie](https://ellie-app.com/32k6kCJxsK6a1/0)

When tying [Invisible reCaptcha](https://developers.google.com/recaptcha/docs/invisible) to a Button element with the `ripple` property the following error occurs

```
Uncaught TypeError: Cannot read property 'elm_event_node_ref' of undefined
    at applyPatch (main.js:195)
    at applyPatchesHelp (main.js:195)
    at applyPatchReorder (main.js:197)
    at applyPatch (main.js:195)
    at applyPatchesHelp (main.js:195)
    at applyPatches (main.js:195)
    at updateIfNeeded (main.js:203)
```

Workaround - do not use ripple on submit buttons for forms protected by reCaptcha.

**Comment by OvermindDL1** [comment]
That is not an elm-mdl bug but is rather a design aspect of elm that outside javascript should-absolutely-never-touch-Elm's-dom.

**Comment by zgohr** [comment]
Alright, I've figured this out. You're absolutely correct, the issue is due to the reCaptcha script modifying the DOM. Still strange how it only happens for ripple buttons but regardless, the _best_ solution I've come up with is to trigger the reCaptcha `render`, `reload`, and `execute` all through ports. This way, the only DOM changes made by reCaptcha is the badge getting added as an element at the bottom of the `body`, which I believe is outside of Elm's jurisdiction even when using `fullscreen`.

edit: if anyone runs into this and needs more specifics on getting this working just let me know and I'll get an updated Ellie together.
