### ISSUE TITLE
How can I change url after clicking on tab ?

### ISSUE THREAD

**Issue by yok0** [debois/elm-mdl#308]
Probably noob question but just getting started. How would one make url change after clicking on the tab. Had navbar as a links, decided to try mdl and Im stuck at the moment. Any help much appreciated.
https://ellie-app.com/33RgGQ4Vztya1/3

**Comment by aforemny** [comment]
Hi,
changing the URL is currently not supported by elm-mdl. You would want to use [elm-lang/navigation](http://package.elm-lang.org/packages/elm-lang/navigation/latest).
