### ISSUE TITLE
TextField code sample is missing a field

### ISSUE THREAD

**Issue by happysalada** [debois/elm-mdl#309]
This is a screenshot of the current code example for the textfield doc
<img width="1280" alt="screen shot 2017-04-30 at 3 06 20 pm" src="https://cloud.githubusercontent.com/assets/5317234/25562079/9ebbbdac-2db6-11e7-94b3-6f64d9f60868.png">

Where as the correct code should be 
```
Textfield.render Mdl [0] model.mdl
  [ Textfield.label "Age"
  , Textfield.floatingLabel
  , Textfield.value model.age
  , Options.onInput (String.toInt >> ChangeAgeMsg)
  ]
  []
```
Note the empty square brackets at the end.

That causes an error that is not easy to debug.
I would make a PR but I just don't know how to make a PR on the docs

ref [textfield doc page](http://package.elm-lang.org/packages/debois/elm-mdl/8.1.0/Material-Textfield)

**Comment by aforemny** [comment]
Resolved in c2ed8581a9a1e4009b422763b48a460c907fbd69. Thank you for reporting!
