### ISSUE TITLE
Including elm-autocomplete with Material Styling

### ISSUE THREAD

**Issue by thebritican** [debois/elm-mdl#31]
Hi! I'm the author of [elm-autocomplete](http://package.elm-lang.org/packages/thebritican/elm-autocomplete/2.0.0/Autocomplete) and I'd love to add this component to the material design lite suite of components.

Currently, my component strictly follows the elm architecture with `init`, `update` and `view` as the only essential functions exposed. You can see in the [example code](https://github.com/thebritican/elm-autocomplete/blob/2.0.0/example/src/AdvancedExample.elm) for integrating this component into an Elm application, that all the styles for views of the component are injectable via a function mapping an exposed union type to `Html.Attribute` (This API might change slightly to return `List String` instead to limit customization to solely css class names).

I made this issue as a point of discussion: Would you like the implementation of components in this library to be strictly homogenous? If not, I could make a PR with `elm-autocomplete` as an `elm-mdl` dependency. Then, I would add a module that wraps the `Autocomplete`, adding the necessary material animations and stylings. This will also be a good chance to see where my API is limited, so a definite win-win.

What are your thoughts on this? And thanks for writing this library!

P.S. I was actually in the room during the video call during the Elm hack night on Tuesday and thought you explained your reasons for the current architecture quite well. I hope we can solve the problem of material design, bootstrap, foundation, and other styled component libraries being ditched in projects when heavy style customization is necessary. I think by providing a pure functional interface for mapping styles to component views, developers will not have to reimplement the core logic and behavior of these components themselves.

**Comment by debois** [comment]
Hi Greg!
> Currently, my component strictly follows the elm architecture with init, update and view as the only essential functions exposed. You can see in the example code <https://github.com/thebritican/elm-autocomplete/blob/2.0.0/example/src/AdvancedExample.elm> for integrating this component into an Elm application, that all the styles for views of the component are injectable via a function mapping an exposed union type to Html.Attribute (This API might change slightly to return List String instead to limit customization to solely css class names).
> 
> I made this issue as a point of discussion: Would you like the implementation of components in this library to be strictly homogenous? If not, I could make a PR with elm-autocomplete as an elm-mdl dependency. Then, I would add a module that wraps the Autocomplete, adding the necessary material animations and stylings. This will also be a good chance to see where my API is limited, so a definite win-win.
> 
> What are your thoughts on this? And thanks for writing this library!
> 
Such a PR would be awesome!

The components of elm-mdl are all components in the TEA sense. The “Component support” that I discussed with Evan the other day is just a means of taking a bunch of TEA components and converting them to be homogenous. So if elm-autocomplete is already a TEA component, it should fit right into elm-mdl.

The only difficult/interesting bit would be the actual integration of elm-autocomplete with elm-mdl. For that, I propose you look at how to integrate elm-autocomplete specifically with the textfield <https://github.com/debois/elm-mdl/blob/master/src/Material/Textfield.elm> component?

Tips:
	- Ignore the whole “component support” business.
	- You might want to use the sample using elm-mdl with plain TEA <https://github.com/debois/elm-mdl/blob/master/examples/Component-TEA.elm> for testing.

> P.S. I was actually in the room during the video call during the Elm hack night on Tuesday and thought you explained your reasons for the current architecture quite well. I hope we can solve the problem of material design, bootstrap, foundation, and other styled component libraries being ditched in projects when heavy style customization is necessary. I think by providing a pure functional interface for mapping styles to component views, developers will not have to reimplement the core logic and behavior of these components themselves.
> 
I’m behind that!
>

**Comment by debois** [comment]
Hi Greg, can I add the "in progress" label to this one?

**Comment by thebritican** [comment]
Yep! I'm polishing the autocomplete this week and then making a PR this weekend most likely!

**Comment by debois** [comment]
Excellent—looking forward to the PR!
-- 
Søren Debois
+45 5358 5818

**Comment by thebritican** [comment]
Hey sorry this is taking so long! I've been working on getting controlled input support (for uses like @mentions done in my repo [first](https://github.com/thebritican/elm-autocomplete/pull/9)).

When this is done and documented in `0.17` (with the [3.0 release](https://github.com/thebritican/elm-autocomplete/milestones/3.0.0)) I'll make a PR to integrate it!

**Comment by debois** [comment]
No worries—looking forward to seeing the result!

Btw, I’ll be publishing the elm-mdl 0.17 upgrade later today.

**Comment by thebritican** [comment]
Just released [3.0](http://package.elm-lang.org/packages/thebritican/elm-autocomplete/3.0.1/).

Will start the work soon to get a material styled autocomplete into a PR!

**Comment by debois** [comment]
Excellent. You might want to pull; I updated elm-mdl to 0.17.

**Comment by debois** [comment]
Hi Greg, any progress on autocomplete? Is there anything I can do to help?

**Comment by thebritican** [comment]
I was waiting on some `virtual-dom` fixes that got merged in last week! Now the component works properly in Elm `0.17`. I planned on making that PR this weekend! I'll let you know if I need any help but I have plenty of example code to work off of! We can chat on the PR thread as well

**Comment by debois** [comment]
Absolutely! 

Just of curiosity, what did you need in virtual-dom?

**Comment by thebritican** [comment]
There was an issue with event listeners not being removed properly that broke the autocomplete when it was controlled inside a textarea

**Comment by thebritican** [comment]
So i've tried placing `elm-autocomplete` into this project on my [fork](https://github.com/thebritican/elm-mdl/commit/251e3489632396053d285c789f6d1c60e45cc368).

I planned on including it as a dependency, so that when more features are added to the library, this repo will reflect that. But I can't seem to use `Html.App.map` since the render function needs a certain type annotation.

The plan was to have base functionality by just calling `Autocomplete.view` and then do material-specific behavior in the `Material/Autocomplete.elm` file. However, I'm not sure how to do this with the current structure.

I can always rewrite / copy the component code from [elm-autocomplete](https://github.com/thebritican/elm-autocomplete) but that seems not ideal.

**Comment by debois** [comment]
Cool!

I'm not entirely certain what the problem with `Html.App.map` is, but I took a guess and maybe a comment directly in your fork. If I didn't get it let me know, and I'll try to find some time to look at it tomorrow. 

Really appreciate the effort!

**Comment by thebritican** [comment]
Using `lift` worked out, i'm working tonight on styling it w/ material lite!

**Comment by debois** [comment]
Hi Greg, any progress?

**Comment by thebritican** [comment]
@debois I do have a working autocomplete w/ material design css! But, after a recent elm meetup and discussion w/ Evan & Richard, we may have crafted a better API. I could send a PR for the current API and then update later, but I'm not sure if you'd like the breaking change in `elm-mdl`. (Not sure if that's how it works).

**Comment by debois** [comment]
Depends—how far off is the improved API? What does the current one look like?

Can I see the current implementation?

**Comment by thebritican** [comment]
I wanted to wait until this got released:
https://github.com/evancz/elm-sortable-table

I'm cleaning up the API design tonight. The current implementation is still up at http://package.elm-lang.org/packages/thebritican/elm-autocomplete/3.3.0/

Sorry this has been so slow, as I've been working through examples the API has shown me limitations. I think this approach where the data is always owned by the application is **much** cleaner.

Tomorrow is another elm hack night, i'll try to push an `elm-autocomplete` PR tomorrow night

**Comment by debois** [comment]
Hi Greg, great—looking forward to the PR!

**Comment by debois** [comment]
Hi Greg, how's the new API coming?

**Comment by thebritican** [comment]
Done! Just need to work on examples. There's currently a blocker, though, since I'm using a native module as a substitute for `Attribute.map`.

You can follow along here:
https://github.com/thebritican/elm-autocomplete/issues/26

I'm cleaning up all the examples, redoing tests, and waiting on
the function requested in https://github.com/elm-lang/html/issues/18
to be released so it's publishable.

This new API will have a lot more capabilities, including separate selection states for keyboard and mouse.

**Comment by OvermindDL1** [comment]
How is this going thus far?  :-)

**Comment by debois** [comment]
@thebritican: With 0.18 out, is this something that can resume?

**Comment by MentalGear** [comment]
Would really like to see thebritican's amazing component in mdl !

**Comment by daniel-kun** [comment]
Hey, I'd really love to use autocomplete with mdl. Any progress? Any way I can help out? cc @thebritican / @debois

**Comment by aforemny** [comment]
We are currently trying to re-organize things a bit and this issue did not make the list. If you would like to continue this discussion, please re-open the issue after we have worked things out on our end in issue #328.
