### ISSUE TITLE
Event onscroll dont work

### ISSUE THREAD

**Issue by darkconsul** [debois/elm-mdl#311]
I wanted to use this code

index.html:
```
window.onscroll = function() {
    scrollFixed();
};
window.onresize = function() {
    resizeFixed();
};
app = Elm.Main.fullscreen();
```
main.elm:
```
view : Model -> Html Msg
view model =
    let 
      body = getCurrentPage model
    in
      Layout.render Mdl model.mdl
        [Layout.fixedHeader]
        {   header = []
          , drawer = drawer model
          , tabs = ([], [])
          , main = [body]
        }
```
ScrollFixed was never called.

But when I commented import Material.Layout and replace view with
```
view : Model -> Html Msg
view = getCurrentPage
```
onscroll started to work normally

**Comment by OvermindDL1** [comment]
Most likely it is not the body scrolling but a child element of layout.  `scroll` events do not propagate upwards, you have to register it on the element itself.

**Comment by darkconsul** [comment]
Oh, i am blind)) Thank you very much, this code is work
```
mdl_layout = document.getElementById('elm-mdl-layout-main');
   mdl_layout.onscroll = function() {
       scrollFixed();
   };

```

**Comment by OvermindDL1** [comment]
@darkconsul Fair warning, elm can replace the dom elements at any point, you should be registering to the scroll event on that element from inside elm, then calling your `scrollFixed()` via a port based on that scroll event, otherwise you may find that function randomly crashing.  :-)
