### ISSUE TITLE
List items with primary actions

### ISSUE THREAD

**Issue by tad-lispy** [debois/elm-mdl#326]
Following this [thread on Elm slack](https://elmlang.slack.com/archives/C12KMAYJX/p1497786238455273)

I'd like to implement a [list item with primary action](https://material.io/guidelines/components/lists.html#lists-actions), similar in behaviour to [list component of Material UI library for  ReactJS](http://www.material-ui.com/#/components/list). On [MDC website](https://material-components-web.appspot.com/list.html) (bottom of the page) they are referred to as *Interactive Lists*.

It should have following features:

- Hover effect
- Ripple effect
- Mouse cursor indicator (`cursor: pointer` in CSS terms)
- Whole item is clickable (provided there is no control for secondary action) 

It's quite similar to how `Material.Menu` behaves, but it should be always open and take entire width of a container (like a list). Also separators would be very welcome.

**Comment by OvermindDL1** [comment]
Sounds fairly simple to make, what issues were you having?

**Comment by tad-lispy** [comment]
Oh, I'm sure it is. I'm just dipping my toes in Elm. 

I'd love to help here, but currently I'm leaning toward building UI for my project with Elm + Web Components. There seem to be a lot of nice and ready to use Material Design components available. I'll see how it goes and maybe get back to Elm-MDL.

Anyway thanks for this really impressive package. Great work!

**Comment by aforemny** [comment]
Hi,
we are currently trying to re-organize the issues and this issue did not make the list. We are trying to focus on bug fixes and I am afraid we cannot come up with a demo for this. If you have a more specific question to an implementation of such demo, please feel free to open another issue. Please understand that for now I am closing this.
