### ISSUE TITLE
Icons are not positioned correctly inside button-links

### ISSUE THREAD

**Issue by SidneyNemzer** [debois/elm-mdl#331]
By "button-link", I mean a `Button` with a `Button.link` attribute. This is rendered as an `<a>` instead of a `<button>`.

Text is fine inside the button-link, but Icons are slightly too high.

Observe:
![image](https://user-images.githubusercontent.com/21203108/27657427-7b46de32-5c01-11e7-90ca-dd34921837d3.png)

**EDIT**: The buttons are different sizes in the picture because of the `box-sizing` property; they are now the same size in the demo, but the icon alignment is still an issue

Live demo: https://ellie-app.com/3BNTD3BkNRWa1/0

I have this issue in the latest version of Chrome and Firefox.

**Comment by SidneyNemzer** [comment]
I finally figured it out!

You just need to add a doctype to the top of the HTML page (eg `<!doctype html>`)

**Comment by aforemny** [comment]
Thank you for figuring this out. I scratched my head on it for a while already, not liking the solutions I came up with... so. Great!
