### ISSUE TITLE
Textfield does not dispatch internal messages when user messages are installed

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#333]
I think this is the root cause of some Textfield issues, as mentioned in some of their comments. I've come up with a fix in 6feddc44f38b7fefa3063bbae0f8ecae05e5f85d. I have some second thoughts about the code and will leave this open for a while. Feedback appreciated.

**Comment by aforemny** [comment]
@vipentti With regards to #164, is commit 6feddc44f38b7fefa3063bbae0f8ecae05e5f85d the way to go? Does that mean we do not need to have the focusin/focusout polyfill anymore?

**Comment by aforemny** [comment]
I think this is the way to go. For now, only Textfield uses this, see #338. I also removed the focusin/out polyfill as I think it is not needed anymore (27467d5e7836f0685407610c06bdc665d01356fd).

**Comment by dcbb** [comment]
When will the fix to the labels not disappearing in Textfields shipped? I installed elm-mdl 8.1 with elm-package and I have the issue, but the here it's closed.  Or am I missing something?

**Comment by dan-kihot8** [comment]
And I have problem described by dcbb. I tryied elm-mdl v8 and v9 - no difference.
