### ISSUE TITLE
Textfield doesn't allow changes to padding

### ISSUE THREAD

**Issue by Socratic1** [debois/elm-mdl#337]
div.mdl-textfield has a default top and bottom padding of 20px. When I try to change the padding, the label and animation are no longer positioned correctly on the textfield.

**Comment by aforemny** [comment]
As you've said the assumption of 20px padding is hard-coded in several places of material-design-lite's css.

You have the option to use a stylesheet to override all those occurrences, or to fork material-design-lite's sources and compile the CSS yourself. In the second case, you will only have to adjust 1-2 variables. Unfortunately I do not see a straight forward way to solve this in elm-mdl.
