### ISSUE TITLE
Implement menu component

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#34]
Underway in PR #33.

**Comment by aforemny** [comment]
Merged in feabf9f8100b76373c2a63b48a87806c765c46a6.

**Comment by debois** [comment]
Ok, good. I'll take a look as soon as possible, but likely not before sometime tomorrow evening. (Similarly for Tables; my gut feeling is you should allow arbitrary html, but I need to spend some time looking at the details.)

**Comment by debois** [comment]
Hi Alexander, I integrated the Menu component into some stuff I'm doing to streamline the use of Parts, and got to take an even closer look in the process. It's really impressive work you've done!

Could you look me up on the elm-slack (@debois)?
