### ISSUE TITLE
Scrolling up leads to stuttering animation

### ISSUE THREAD

**Issue by arnehormann** [debois/elm-mdl#35]
On https://debois.github.io/elm-mdl/#/badges, scrolling up leads to a stuttering animation (the header bar starts folding, unfolds again - this repeats 6 or 7 times).

No other page in the demo triggered it - but that page is the only one where the content exactly fits into my viewport.
I guess it's an unintended interaction between starting the folding animation and checking the available space to see if folding is necessary.

**Comment by debois** [comment]
Thanks. Should be fixed in current point-release?

**Comment by arnehormann** [comment]
I just checked - bad news.

Now it folds correctly, but opposed to all pages, it doesn't unfold on scrolling down andI can't get back to the tabs (I can when I click on the hamburger menu).

**Comment by arnehormann** [comment]
@debois direct mention because i don't know if github informs on comments for closed issues...

**Comment by debois** [comment]
It's an upstream issue; Google's MDL behaves the same. You can click the header to get it back, though.

**Comment by debois** [comment]
Strike that, no easy fix. See this PR: google/material-design-lite#86.
