### ISSUE TITLE
Implement table component

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#36]
Could you assign me to this one? I'm planning to do tables next.

**Comment by aforemny** [comment]
This is my preliminary implementation for tables: aforemny/elm-mdl/tables.

They currently use HTML check boxes instead of `Toggles`. The check box in the table's header selects/deselects all rows of the table, and thus SelectAll decodes this number from DOM.

Using `Toggles` seems to be straightforward until this point: how could I run a `Decoder a` on the `Toggle`'s `Change` action?

The solution seems to me to handle the click event in the table and convert that to a `Change` event to send to the `Toggle`. How would I do that?

**Comment by debois** [comment]
Maybe you could install an onClick handler on the div parent to the toggle?

**Comment by aforemny** [comment]
Just an update that the implementation now uses Toggles. :) Am I using `Toggles.fwdChange` correctly?

I think I will rework this quite a bit, because I do not want the table to maintain any state related to it's items, ie. selected or not selected. Because that leads to a lot of bookkeeping between ones actual data and your data displayed in a table. Same goes for sorting, which is currently not implemented.

Demo: https://aforemny.github.io/elm-mdl/#/tables

**Comment by aforemny** [comment]
I thought about it a bit more, and I am not convinced anymore that what I said is true. I would suggest that I finish the implementation of tables as it is, and we see from there. OK?

Also, if I implement sorting on the table level, I will continue to constrain table cells to contain strings. Do you think that is OK for a first implementation?

**Comment by debois** [comment]
I looked at the implementation over on https://github.com/aforemny/elm-mdl/tree/tables. 

I can't work out exactly how Toggles appear in the Demo: Does tables always include checkboxes? I think it'd be nicer to adopt an API a la Grid, where there is a constructor function for rows and cells, which accepts `Style` to indicate sorting-options etc. You may want a special constructor for a checkbox row.

**Comment by aforemny** [comment]
(I also needed to take some time off, no worries! :))

The current implementation is a prototype in respect to that I wanted to test all features in one table, then add customization options.

I will try this week to finish the implementation to a point that I consider "right" for the moment, and we'll talk from there. I still have to wrap my head around the right abstraction for tables and as this will take me some time, I'd rather have some working implementation first, so that we can achieve full component support sooner.

**Comment by debois** [comment]
Sure, absolutely.

**Comment by shmish111** [comment]
Did you manage to get this to a point where at least a basic functionality could be merged? @aforemny I looked at your fork demo and it seemed to work very well.

**Comment by aforemny** [comment]
@shmish111: Tables in MDL offer 1. styling and 2. the functionality of selecting rows via toggles and 3. the functionality of *indicating* a header as sorted.

With my initial pull request, I wanted to implement (a), (b) and (c) with the option of auto-sorting. Having worked with tables a bit more, I am now tending to only implement (a) here, giving users the options of doing (b) and (c) themselves. This is a much simpler API, and we are avoiding some hacks that are required to make (b) and (c) work together.

I will try to push an update today.

**Comment by aforemny** [comment]
I pushed the newest code to https://github.com/aforemny/elm-mdl/tree/basic-tables.

I do like the API in `Material.Table` and I think not including the option to auto-checkbox the table is the right call. However, I do not like how integration in `Demo.Tables` turns out, but I cannot invest more time investigating right now.

@debois: Do you agree on the new and more basic interface in `Material.Table`, especially removing auto-checkboxes from tables?

Demo is live at http://aforemny.github.io/elm-mdl/.

Comments appreciated!

**Comment by shmish111** [comment]
@aforemny what is auto-sorting? I like that the table doesn't 'do' much, sorting for example needs to be down to the user, in my case I need to go back to my backend and get a sorted data set. For this I want to use TEA and have an `onClick` function to send a `Sort` message and then update my view with MDL Table options as you indicated. I haven't looked at Toggles yet but I can see why it might be difficult, isn't it the job of Toggles to get around this difficulty rather than Tables though?

FYI elm and mdl noob.

**Comment by debois** [comment]
@aforemny: Yes. I'd like it if we could make sure that implementing toggling directly could be more convenient than it appears at a brief glance of your current demo, but that's a problem for the Toggle component, not for tables.

**Comment by shmish111** [comment]
@debois @aforemny what would it take to get the tables implementation merged? Is there anything I could do to help?

**Comment by aforemny** [comment]
I prepared a new commit that I want to merge. By dropping `Toggles` tables are purely cosmetic. I exported `view` and `render` for convenience (?), but they are kind of a no-op.

I have one problem left to tackle: In the demo if you click on the first header it should fire the `Click` event, so that I can change the sorting order. I think this was done usually by exposing an `onClick` handler in `Material.Table`, but I was wondering if this could not be externalized. Even if it can, I don't know if it should be, as it might break components, right? Is that point still valid because tables are purely cosmetic, ie. they do not have any functionality? @debois, could you advice me on that? I'd prefer a quick solution to this, rather than a perfect one. So I should implement `onClick`, right?

@shmish111: Is this implementation sufficient for your use case right now?

Comments appreciated. If there are no objections I will merge this. :)

[aforemny/basic-tables](https://github.com/aforemny/elm-mdl/tree/basic-tables)
[demo](https://aforemny.github.io/elm-mdl/)

**Comment by shmish111** [comment]
@aforemny the only thing that concerns me is the clicking to sort. I need that event to be exposed so that I can change the ordering myself, I may want to go to the back end to get the sorted data. E.g. I have 10,000 items sorted by date I will show the newest 10, if I click on the date heading in the table, I want the UI to fetch the oldest 10 from the back end.
