### ISSUE TITLE
Can't change table size

### ISSUE THREAD

**Issue by reginaldlouis** [debois/elm-mdl#360]
Maybe I'm doing this incorrectly, but no matter how I set the width of the table, directly or indirectly by changing is parent div (i.e ```Options.div [ Options.css "width" "100px" ] [...]```), the Mdl table ALWAYS have the same width!

It is by design or their is a work around?

**Comment by xAt0mZ** [comment]
Actually the `mdl-data-table` css-class is forcing a style that you can't really control to follow the Material Design specifications. You can find all the references [here](https://debois.github.io/elm-mdl/#tables)

**Comment by reginaldlouis** [comment]
Ok thanks!
