### ISSUE TITLE
Table.numeric is applying non-numeric css

### ISSUE THREAD

**Issue by xAt0mZ** [debois/elm-mdl#366]
Hello there,

I did a copy/paste of the static table code from here : https://debois.github.io/elm-mdl/#tables and the generated html and css is the exact opposite of what is expected and displayed in the live code page. All td created as `Table.numeric` are `cell--non-numeric` and all the others are considered as numeric.

Here is what is expected :
![2018-01-03-170600_1983x337_scrot](https://user-images.githubusercontent.com/7642331/34528612-b0c2b1c0-f0a9-11e7-98c1-f542a34058e2.png)

Here is the code I used :
![2018-01-03-170415_780x382_scrot](https://user-images.githubusercontent.com/7642331/34528617-b575bf5a-f0a9-11e7-903a-2b3baca57268.png)

Here is the result of my code :
![2018-01-03-170502_1905x401_scrot](https://user-images.githubusercontent.com/7642331/34528623-b970c35c-f0a9-11e7-9278-7f60f24c12f0.png)

Using :
* elm-mdl v8.1.0
* elm 0.18.0
* material.css generated with [https://getmdl.io/customize/index.html](https://getmdl.io/customize/index.html)

**Comment by xAt0mZ** [comment]
I believe the issue is coming from here :
https://github.com/debois/elm-mdl/blob/master/src/Material/Table.elm#L199
https://github.com/debois/elm-mdl/blob/master/src/Material/Table.elm#L278

**Comment by xAt0mZ** [comment]
Ok. Nevermind, the bug isn't there on the new-v8 branch (commit [78891390c754c6621d8630dd30125f5797291c0b](https://github.com/debois/elm-mdl/commit/78891390c754c6621d8630dd30125f5797291c0b))

Would be a pleasure if you can release the new-v8 branch as 8.2.0 :)

**Comment by Kurren123** [comment]
This isn't fixed yet, what can I do to solve this?
