### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by wfranzini** [debois/elm-mdl#367]
Hi, 

the demo at https://debois.github.io/elm-mdl/ does not render correctly since the browser is unable to find
`material.teal-red.min.css`.  It seem to have disappeared from code.getmdl.io.

It however is possible to obtain the file from getmdl.io to be served from the same host.

**Comment by xAt0mZ** [comment]
Working for me, make sure you don't have any filter or content blocker activated ?
The [css](https://code.getmdl.io/1.3.0/material.teal-red.min.css) does actually exist.

**Comment by wfranzini** [comment]
@xAt0mZ is right.  For some reason Privacy Badger is blocking code.getmdl.io on my laptop with chromium 63.

Sorry for the noise.
