### ISSUE TITLE
Password Field

### ISSUE THREAD

**Issue by mmport80** [debois/elm-mdl#37]
I looked at the source and docs and couldn't spot how or whether to specify password input text fields

**Comment by debois** [comment]
It's not implemented yet. Ideally, it'd be a Style argument to Textfield, but I haven't gotten around to that yet.

**Comment by debois** [comment]
Turns out to be trivial; I published a new version (3.0.0 because the `Kind` type in Textfield changed, but it really isn't a major change). See [here](https://github.com/debois/elm-mdl/blob/3.0.0/demo/Demo/Textfields.elm#L152-L159) for example use.

**Comment by mmport80** [comment]
Yup, I noticed that too - just wasn't sure how you'd want to handle it
(hence no pr from me : ) Thanks

**Comment by mmport80** [comment]
It works! Thanks!

**Comment by debois** [comment]
Welcome :)
