### ISSUE TITLE
Elm 0.19 support

### ISSUE THREAD

**Issue by bohdyone** [debois/elm-mdl#377]
Hi,

Just opening this issue to ask about Elm 19 support.

Is it planned for the near future?
Is there an approximate timeframe?

Thanks!

**Comment by SidneyNemzer** [comment]
Unfortuantly, it's unlikely that this library will be updated. The upstream library, Material Design Lite, has stopped receiving feature updates, in favor of Material Components Web.

@aforemny is working on two updated libraries:

* [aforemny/elm-mdc](https://github.com/aforemny/elm-mdc) -- Similar to elm-mdl but based on MCW
* [aforemny/elm-mwc](https://github.com/aforemny/elm-mwc) -- Similar styling to aforemny/elm-mdc but using custom elements (which should eliminate the need to pass around the state of UI components)

**Comment by bohdyone** [comment]
Hi,

Thanks for the info. I'll check out those other projects!
