### ISSUE TITLE
Unable to Import Material Helpers

### ISSUE THREAD

**Issue by mmport80** [debois/elm-mdl#38]
Whenever I try the to import the Helpers module compiler complains about not being able to find it.

"I cannot find module 'Material.Helpers'."

This was a problem with 2.1 and now with 3.

Every other module is OK...

**Comment by mmport80** [comment]
Oh, I see, not included in the package's 'elm-package.json' file.

Unsure if you want to include, but some of the demos rely on this.

**Comment by debois** [comment]
Good point. Fixed in 3.1.0

**Comment by mmport80** [comment]
great
