### ISSUE TITLE
no onClick function for Layout.link

### ISSUE THREAD

**Issue by shmish111** [debois/elm-mdl#43]
I’m not using any routing, so how can I get a `Layout.link` to emit a message?
with an `a` I could use `onClick`, how can I do this with `Layout.link`?

**Comment by debois** [comment]
You can't right now. Workaround for now:

    a [ class "mdl-navigation__link", onClick MyClickMessage ] [ text "Click me!" ]

**Comment by debois** [comment]
I'm considering what would be a proper solution. Could you show me some code using the workaround?

**Comment by shmish111** [comment]
I have a navItem function
```
navItem : Search -> Html Msg
navItem search =
    a
        [ onClick (SelectSearch search)
        , class "mdl-navigation__link"
        ]
        [ text
            (case search.unread of
                Nothing ->
                    search.name

                Just unread ->
                    search.name ++ "(" ++ (toString unread) ++ ")"
            )
        ]
```

and in my Main.elm I map it over a list of things in my model

```
searchNavItem : Searches.Search -> Html Msg
searchNavItem search =
    App.map SearchesMsg
        (Searches.navItem search)


drawer : Model -> List (Html Msg)
drawer model =
    [ Layout.title [] [ text "Searches" ]
    , Layout.navigation []
        (List.map searchNavItem model.searchesModel.allSearches)
    ]
```

Does that help?

**Comment by debois** [comment]
Yes, thanks. There'll be a proper API for adding href/onClick in the next release. That might be some way off you; is the work-around above enough in the meantime?

**Comment by shmish111** [comment]
@debois Yes work around is fine thanks :)
