### ISSUE TITLE
fixedDrawer and Responsiveness

### ISSUE THREAD

**Issue by demsullivan** [debois/elm-mdl#44]
I was playing around with the `Layout.fixedDrawer` option and it seems to create issues on screens where the drawer is hidden - my understanding is that `fixedDrawer` makes the drawer fixed on large screens, but hidden on small screens. It is hidden, but there's a large space between the hamburger icon and the rest of the header.

Here's what the issue looks like:

On displays 1024px and smaller:
![1024px and smaller](https://cloud.githubusercontent.com/assets/3767534/15802706/58309eb0-2a89-11e6-8f26-c0134472f1c0.png)

On displays larger than 1024px:
![greater than 1024px](https://cloud.githubusercontent.com/assets/3767534/15802707/583d6e06-2a89-11e6-8e9c-3888eb31dcdc.png)

**Comment by debois** [comment]
This should be fixed in 5.0.0, just out.
