### ISSUE TITLE
Top aligned menus don't behave correctly after selecting an Item

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#46]
As witnessed currently in the demo, if you select (click) a menu item of one of the bottom menus and open it again, the items are not aligned properly.

I have an implementation that fixes that, but I have yet to figure out why. In any case, I will push the fix shortly.

**Comment by debois** [comment]
Hi @aforemny: was this fixed in 272cbe05c5e3820be819388c2c1626a60027f816?

**Comment by aforemny** [comment]
No, it's not.
