### ISSUE TITLE
Implement Dialog component

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#52]
See [here](https://getmdl.io/components/index.html#dialog-section).

**Comment by aforemny** [comment]
I took a quick look at the Material Design Lite implementation of dialogs. According to the (dialog section)[https://getmdl.io/components/index.html#dialog-section], dialogs are _not_ supported by the majority of browsers and thus have to be (polyfilled)[https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js].

As far as the polyfill is concerned, it seems to deal with at least the following aspects:

1. positioning of the dialog
2. adding a backdrop that cancels mouse events outside the dialog
3. stacking open dialogs
4. setting focus

Apart from that, dialogs are purely cosmetic and trivially re-implemented in Elm.

I propose the following:

In a *first implementation*, we should come up with a single dialog component that satisfies 1. and 2. This would allow people to use simple (singleton) dialogs, and if necessary implement something more sophisticated in their application themselves.

In a *second implementation*, a simple dialog manager could solve 3. by computing z-indices for a stack of dialogs and the backdrop.

As far as 4. is concerned, we have not yet come up with a good way to deal with focus at all. So this should not be a concern for now. One could, however, investigate if the `autofocus` attribute could do anything sensible here.

**Comment by debois** [comment]
I like your plan. 

Would we have really easy path to fully functioning Dialogs if we required the user to load a polyfill, though?

**Comment by puhrez** [comment]
@debois I'm really interested in working on this feature, with the idea of limitted browser support at first then polyfill. 
I'm new to this project and new(ish) to elm, any advice where I could get started?

**Comment by debois** [comment]
Gentlemen, 

@puhrez provided a very nice PR, neatly settling the API on the elm side, taking the first steps of @aforemny's plan, stopping short of adding open/close capabilities. Many thanks, and welcome to elm-mdl!

I've added those capabilities. As it happens, I couldn't find a way to open a modal dialog without calling `dialog.showModal` from Javascript, using the usual inline-JS-in-event-handler hack. I tried to be real careful about everything being defined to prevent our use of JS from blowing up the elm runtime. @vipentti, could you take a look? [These](https://github.com/debois/elm-mdl/blob/master/src/Material/Dialog.elm#L99-L163) are the operative lines. 

The current implementation has the following limitations (I also wrote these in the docs of `Dialog.view`):

- Using  [the
polyfill](https://github.com/GoogleChrome/dialog-polyfill) places [these
restrictions](https://github.com/GoogleChrome/dialog-polyfill#limitations) on
where in the DOM you can put the output of this function.
- We currently support only one dialog pr. application. Installing more than one dialog will result in a random one showing. 

I've tested this implementation on Chrome, Safari and Firefox, where they seem to function flawlessly. Could someone try some IE/Edge browsers?

I'm a bit queasy about our (ok, my) proliferating use of inline JS. Can we live with the present implementation? Is there a JS-free alternative, or at least a nicer one?

**Comment by OvermindDL1** [comment]
The one dialog per application is a bit restrictive.  Is this planned to be fixed before final release?

**Comment by debois** [comment]
It doesn't mean you can have only one fixed dialog; it just means you can only have one at a time, and the way to get a "new" dialog is to change the contents of the one you have?

**Comment by OvermindDL1** [comment]
Ahhh only one-open-at-a-time, makes much more sense, can deal with that.  :-)

**Comment by aforemny** [comment]
@puhrez Thank you for working on this! :)

**Comment by debois** [comment]
Current implementation deemed acceptable after consultation with @vipentti and 64526ad124e861fefccabbac6817d3ebc53b01b2.

**Comment by tomvandezande** [comment]
The only way to open the dialog is via a Dom event. So how could I change the content of the dialog in between the Dom event and the dialog showing?

**Comment by tomvandezande** [comment]
Maybe I'm missing something obvious, but this is the workaround I'm using for know:

Material.Menu.item
  [ Material.Options.onMouseDown (RenderDelDialog)
  , Material.Dialog.openOn "mouseup"
  ]
  [ i "delete", text "Delete" ]
