### ISSUE TITLE
Implement Tooltip component

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#54]
See [here](https://getmdl.io/components/index.html#tooltips-section).

**Comment by vipentti** [comment]
I have done some experimenting with tooltips over the weekend. The tricky part was/is getting the dom event from the tooltips target to the actual tooltip to render it. 

Currently the API looks something like 

```elm
import Material.Tooltip as Tooltip

-- Note the index in both the Render as well as the mouse event handlers

tooltip : Model -> Html Msg
tooltip model =
    div []
    [ div [ class "icon material-icons"
          , Tooltip.onMouseEnter Mdl [0]
          , Tooltip.onMouseLeave Mdl [0]
          ]
          [text "add"]

    , Tooltip.render Mdl [0] model.mdl
        [Tooltip.default]
        [text "Default tooltip"]
    ]
```

**Comment by debois** [comment]
It wouldn't be possible to have `Tooltip` be a `Property something something`? Can I see your current draft implementation?

**Comment by vipentti** [comment]
https://github.com/vipentti/elm-mdl/blob/tooltip-comp-dev/src/Material/Tooltip.elm

and demo

https://github.com/vipentti/elm-mdl/blob/tooltip-comp-dev/demo/Demo/Tooltip.elm

**Comment by vipentti** [comment]
Also it might be, I did not think or try that, it could possibly be even simpler in that case.

**Comment by debois** [comment]
I looked over the source: Very nice—that's very sophisticated use of the parts model! I'm very much looking forward to the pull request!

I see why you need the separate `onMouseEnter` and `...Leave` handlers, and I don't see a good way to get rid of them for end users. 

I have a few suggestions: 

(1) It's a point of elm-mdl that you don't have to use the Parts model if you don't want. Your current tooltip doesn't allow that (right?). Could you implement `onMouseEnter` and `onMouseLeave` variants for use without parts?

(2) For the Parts variant (that is, the current implementation) I think you could combine the `onMouseEnter` and `onMouseLeave` handlers into one _roughly_ like this: 
   
    attach lift index = 
      Options.many 
        [ Material.Options.Internal.attribute <| onMouseEnter lift index 
        , Material.Options.Internal.attribute <| onMouseLeave lift index
        ]

With this, we can re-phrase the demo:

                    tooltip : Model -> Html Msg
                    tooltip model =
                      div []
                        [ Icon.view "add" [ Tooltip.attach Mdl [0] ]
                        , Tooltip.render Mdl [0] model.mdl
                            [Tooltip.default]
                            [text "Default tooltip"]
                        ]

(3) Can we get `Tooltip.default` to be an actual default so that you don't have to specify it?

**Comment by debois** [comment]
Very good with (2) and (3). With (1), I'm a little bit confused: doesn't (2) do more or less what you outline in (1)?

**Comment by vipentti** [comment]
Regarding (1). I think it would have been mostly for the non-material (Html m) nodes where attaching multiple properties isn't possible as far as I know.

I'll implement (2). and see how it works out, maybe the first is not needed then at all

**Comment by debois** [comment]
Ok—looking forward to seeing it!
