### ISSUE TITLE
Implement Tabs component

### ISSUE THREAD

**Issue by debois** [debois/elm-mdl#56]
See [here](https://getmdl.io/components/index.html#layout-section/tabs).

**Comment by vipentti** [comment]
Assuming no one else has started this I could start working on this one next.

**Comment by debois** [comment]
Not to my knowledge—let's say it's yours :)

You may be able to re-use, either by refactoring or copy-paste, parts of the tabs in Layout.

**Comment by aforemny** [comment]
Merged in 1b0cecbcbcc56d53672be1cb8e80e6988ce0a21d.
