### ISSUE TITLE
Cannot Import Material.Menu

### ISSUE THREAD

**Issue by SauceWaffle** [debois/elm-mdl#59]
Thanks for the contribution, but had an issue when trying to use Material.Menu. Unless I am just trying to use it incorrectly, I get an error that I can't import Material.Menu. Was able to fix this by updating the elm-package.json to expose Material.Menu. There were some more missing from the elm-package (Ripple, Shadow, Template, Toggles).

New to Elm, so like I said this could be user error, but this fixed it for me.

**Comment by debois** [comment]
Right you are. I think @aforemny  disabled it in order to fix an important bug before the next release. Alexander?

**Comment by aforemny** [comment]
@debois, I did not intend to disable menus. The other imports @SauceWaffle mentioned are supposted to be internal? If not, just add `Material.Menu` along with them. They API will not change for the fix that I have yet to push (#46).

**Comment by aforemny** [comment]
Seems like I never exposed it… I fixed it upstream. Thanks for reporting, @SauceWaffle! Please open another issue for any other exports you feel are missing!

**Comment by debois** [comment]
Ok, sorry about the confusion!
