### ISSUE TITLE
Allow Change of Menu Icon

### ISSUE THREAD

**Issue by SauceWaffle** [debois/elm-mdl#61]
debois,

Needed to have multiple menus on a page so needed to be able to change what icon displays for them. Attached my version of Menu.elm with the changes, basically just imported Icon, setup an option and changed line 347 to set the Icon as whatever was sent in config. 
[Menu.elm.txt](https://github.com/debois/elm-mdl/files/325893/Menu.elm.txt)

Usage: 
"
userMenu : Models.Model -> Html Messages.Msg
userMenu model =
  div []
  [
    Menu.render MDL [0] model.mdl
    [ Menu.bottomRight
    , Menu.ripple
    , Menu.icon "account_circle"
    ]
    [ Menu.Item False True <| div [] [ text "My Profile" ]
    , Menu.Item False True <| div [] [ text "Log In" ]
    ]

  ]
"

**Comment by debois** [comment]
Looks good! Could you submit a PR?

**Comment by SauceWaffle** [comment]
"It seems you do not have permission to push your changes to this
repository" :(

[image: Inline image 1]

**Comment by debois** [comment]
GitHub has a very neat way to do this, but you have to do it in a particular way. See the GitHub docs [here](https://help.github.com/articles/using-pull-requests/).

**Comment by debois** [comment]
Do you have time to upgrade the .txt file to an actual PR?

**Comment by SauceWaffle** [comment]
Very sorry. I live in Cleveland and our team just won the basketball
championship. It's been crazy and I wasn't near a computer all day
yesterday. I'll have the PR to you today.

**Comment by debois** [comment]
Well, congratulations, then :)

I'll take a look at your PR.

**Comment by debois** [comment]
Closed by #65.
