### ISSUE TITLE
Cannot read property 'button' of undefined

### ISSUE THREAD

**Issue by kittykatattack** [debois/elm-mdl#70]
Hello,

I'm getting the following runtime error when mouse is released over a button:

.js:21787 Uncaught TypeError: Cannot read property 'button' of undefined

The error points to the second line of this code:

```js
function (_) {
			return _.button;
		},
		F2(
			function (x, y) {
				return _elm_lang$core$Native_Utils.update(
					y,
					{button: x});
			}),
```

Here's the module that's producing the error.
Does it look correct or there something important that I've missed?
This a child module in a larger application - Do I need to add any Mdl code to the parent module?

```elm
module Header exposing (Model, Msg, init, update, view ) --where

import Html exposing (..)
import Html.Attributes exposing (..)
import Defaults exposing (..)
import Json.Encode as Json

import Material
import Material.Scheme
import Material.Button as Button
import Material.Options exposing (css)


-- MODEL

type alias Model = 
  { logo : String
  , mdl : Material.Model
  , markdown : String
  }


init : Model
init = 
  { logo = Defaults.imagesLocation ++ "logoTVO_WritersDesk.png"
  , mdl = Material.model
  , markdown = ""
  }


-- UPDATE

type Msg 
  = MDL Material.Msg
  | Download
  | UpdateMarkdown String
  | NoOp


-- port download : String -> Cmd msg


update : Msg -> Model -> (Model, Cmd Msg)
update message model =
  case message of
    Download ->
      -- model ! [ download model.markdown ]
      model ! []

    UpdateMarkdown markdown' ->
      { model | markdown = markdown' }
      ! []

    MDL msg ->
      Material.update MDL msg model

    NoOp ->
      model ! []


-- VIEW

type alias Mdl = 
  Material.Model 

view : Model -> Html Msg
view model =
  div []
    [ img [ src model.logo ] []
    , Button.render MDL [0] model.mdl
        [ Button.onClick Download ]
        [ text "download" ]
    ]
  |> Material.Scheme.top

```

**Comment by aforemny** [comment]
Could you please provide a minimal working example, ie. a stand-alone Elm module that I can compile?

**Comment by aforemny** [comment]
Does the problem persist after deleting `elm-stuff` and rebuilding?

**Comment by kittykatattack** [comment]
Deleting `elm-stuff`and rebuilding worked!
Thank you, I would never have been able to figure this out without your suggestion :smile:

Could you explain why I needed to that, just in case I run into a similar problem again?

**Comment by aforemny** [comment]
I don't know what causes this. I would assume that is has something to do with elm-stuff being in some intermediate state which the compiler cannot handle, ie. if you terminate some compilation in process. It might also be a compiler bug.
