### ISSUE TITLE
Background alpha for button roll-over states?

### ISSUE THREAD

**Issue by kittykatattack** [debois/elm-mdl#71]
Hello,

Just  a quick question:
Is it possible to change the alpha value for the rectangular background in the flat button rollover state?

Thanks!

**Comment by aforemny** [comment]
What do you mean by rollover state? Do you mean the background color when you hover it with the mouse?

**Comment by kittykatattack** [comment]
Yes, that's right - the background hover color

**Comment by aforemny** [comment]
This is currently not possible. With `:hover` being a pseudo-selector it will likely never will be. However, you can compile Google's (material-design-lite)[https://github.com/google/material-design-lite] yourself and include the generated CSS stylesheet `index.html`. The material-design-lite library makes it sufficiently easy to customize the color scheme.

**Comment by kittykatattack** [comment]
Thank you!

**Comment by debois** [comment]
If you prefer, you may be able to override part of the MDL CSS from elm with `Options.stylesheet`. See [here](https://github.com/debois/elm-mdl/blob/master/demo/Demo.elm#L358-L405) and [here](https://github.com/debois/elm-mdl/blob/master/demo/Demo.elm#L287).
