### ISSUE TITLE
Implement select/dropdown component

### ISSUE THREAD

**Issue by aforemny** [debois/elm-mdl#79]
I made some progress implementing a select component, loosely based on the appearance of the Google Polymer [paper-dropdown-menu](https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html). I wanted to share my progress, in case anyone else is working on it or would like to join the discussion.

The code currently lives in my [elm-mdl/extras](https://github.com/aforemny/elm-mdl/tree/extras) branch. You can find the demo [here](http://aforemny.github.io/elm-mdl/#select).

**Comment by debois** [comment]
Very cool. Maybe you can re-appropriate Textfield styling to get the colored bar expanding, like in Polymer?

**Comment by aforemny** [comment]
Yes! I will. Let me gather here what I still want to do before opening a PR.

- [ ] Add colored bar to textfield
- [ ] Add ripple to textfield
- [ ] Add ripple to menu
- [ ] Apply clipping to menu items
- [ ] Make index 0-based (currently 1-based, as in menus)
- [ ] Allow `Html m` inside items (currently `String`)

There are some areas where I am unsure about.

- Featuring keyboard controls, I have to color the selected menu. material design lite offers this, but I am using the wrong background color. Support for this should be added to menus first, and then this component should adapt it.
- The menu closes on the textfields `blur` event. The textfield blurs before the menu can register a click (`Select`) event. So I have to delay the menu's `Close` action for the select to fire. I am unsure whether this is a hack, or a solution. Possibly, solving #68 sheds some light on this.

**Comment by debois** [comment]
I'd like to take over this one if you don't mind? I have a concrete idea of how to re-use stuff from Menu to do it.

**Comment by aforemny** [comment]
Plesae do!

**Comment by AlexKovalevych** [comment]
This one is a must have feature!

**Comment by knewter** [comment]
what namespace should things that aren't in the MDL spec itself live under?  I personally would love to see more extras like this but think it seems reasonable for them to not be something like `Material.Dropdown` since such a thing doesn't exist in the reference library...just a thought/wrench to throw in :)

(but also though I hate the brusqueness I'm strongly tempted to PR in a link to http://fuckdropdowns.com in the docs)

**Comment by OvermindDL1** [comment]
It does exist in the Material Spec though (and is incoming in mdl, mdl is just slow and far behind the spec).  However I'd say put it in something like `Material.Extras` or so until it finally gets added into mdl proper and can be replaced (or keep both versions in the different namespaces if they are different in functionality enough).

**Comment by debois** [comment]
I just watched that video from your link on the elm-slack, and it is persuasive (if, ah, borderline uncouth). I'm not sure about linking it—I'm not a native speaker, so I sometimes have trouble gauging exactly how profane swearing actually is.

We discussed how to deal with extra components, and agreed that we want it and want to encourage it. We didn't reach a conclusion about exactly how to integrate them. `Material.Extra` is definitely an option.

**Comment by OvermindDL1** [comment]
I'd personally say not linking such a thing.  Coming from a business perspective such a thing would cause something to not be used.

**Comment by knewter** [comment]
I should have wrapped that in <snark></snark> tags.  I was being silly but I *do* love sharing that link because it's persuasive...just wouldn't recommend it show up in a Real Project's Documentation...sorry for the noise!

**Comment by martindlarsson** [comment]
Is this feature coming soon? I was actually surprised that dropdowns was not in here already. Would love to use MDL instead of mixing standard Html and miss out on the styling. Looks a bit weird when all components are mdl styled except the dropdowns.

**Comment by aforemny** [comment]
@martindlarsson I will want to include it in the next release which will be based on the msg branch. Until then, would it help you if I update the PR to compile against master?

Closing in favor of #282.
