### ISSUE TITLE
Toggles: default value for ripple should be false?

### ISSUE THREAD

**Issue by slegrand45** [debois/elm-mdl#80]
Hello,

The ripple value in the default config of toggles is set to true: https://github.com/debois/elm-mdl/blob/master/src/Material/Toggles.elm#L121

But as it seems there is only a function to set this option to true and none to set it to false, i guess the default value should be false?

Stéphane.

**Comment by debois** [comment]
You're right, thanks for pointing this out. I merged your PR :)

**Comment by debois** [comment]
You're right, thanks for pointing this out. I merged your PR :)
