### ISSUE TITLE
Weird rendering bug on Firefox, when Menu is opened and closed again

### ISSUE THREAD

**Issue by anfelor** [debois/elm-mdl#83]
On Firefox 47 on Fedora Linux:
![17-07-2016_08 59 49](https://cloud.githubusercontent.com/assets/16764214/16899241/d7b189ee-4bfc-11e6-9d8a-a6a1a84629b7.png)
The Menu is closed but the borders stay. They disappear, when scrolling or switching browser tab.

**Comment by piyushchauhan2011** [comment]
Could you provide a github repo or js fiddle @anfelor? Would be helpful in debugging.

**Comment by anfelor** [comment]
Sorry, should have been more clear: 
The screenshot is from the official home page: https://debois.github.io/elm-mdl/#menus

(js fiddle supports elm?)

**Comment by slegrand45** [comment]
FWIW, i can see the same rendering bug with the "native" MDL demo: https://getmdl.io/components/index.html#menus-section

**Comment by debois** [comment]
I can't reproduce this on Firefox 47.0.1, neither in the [elm-mdl demo](https://debois.github.io/elm-mdl/#menus) or [upstream](https://getmdl.io/components/index.html#menus-section). Could you give exact steps to reproduce?

**Comment by debois** [comment]
@piyushchauhan2011: could you look me up on the elm slack (@debois) when you have the time?

**Comment by anfelor** [comment]
I can confirm that it also happens on the official MDL demo.
Also: https://github.com/google/material-design-lite/issues/4549
@debois:
 - Open the menu
 - Click on any menu item
 - Sometimes the bug doesn't occur, so try at least 5 times.

As it appears also on other pages, this might be a bug in Firefox.
I'm leaving it open nonetheless to see, whether someone has an idea on how to fix it.

**Comment by slegrand45** [comment]
And the bug seems to happen only on Linux/FreeBSD. I just tested on Firefox for Windows 10 and the rendering is right.

**Comment by anfelor** [comment]
Created bug for Mozilla Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1288059

**Comment by debois** [comment]
Ok, since this seems to be a Firefox-issue, I won't be doing anything more on this. Object to re-open.

**Comment by aforemny** [comment]
As this is still present for me in Firefox 47.0.1, I investigated a bit and I think I can narrow it down to the following CSS properties on `mdl-menu__outline` used in conjunction: `transition: transform` and `scale(0)`. Removing either `transition: transform`, or setting `scale(0)` in CSS fixes it for me.

I'm not saying we should do any of that here. I just wanted to report my results in case anybody else is intersted.

**Comment by debois** [comment]
Can we set `scale(0)` directly on the element? I wouldn't mind doing a workaround if it doesn't have adverse side-effects?

**Comment by aforemny** [comment]
My bad, I meant setting `scale(1)` fixes it for me. Let's not do that as it messes up the menu's open animation. It is not a proper fix. I just wanted to mention how I would work-around that if I had to.
