### ISSUE TITLE
Shouldn't switching between tabs also scroll to top?

### ISSUE THREAD

**Issue by anfelor** [debois/elm-mdl#84]
The spec isn't clear about this, but it is implemented like this on the official mdl page: [https://getmdl.io/](https://getmdl.io/)

EDIT: Apparently switching tabs on [https://debois.github.io/elm-mdl/](https://debois.github.io/elm-mdl/) *does* make the browser scroll to top, but only Chrome; in Firefox 47 on Linux the content changes but the page stays scrolled down.

**Comment by debois** [comment]
They should, thanks. I'll look into this.
