### ISSUE TITLE
Toggles in Layout.fixedHeader

### ISSUE THREAD

**Issue by jschoch** [debois/elm-mdl#94]
Toggles do not render correctly in a fixed header.  False renders ok, but when the value is True it does not.

```elm
Toggles.switch MDL [0] model.mdl
        [ Toggles.onClick ToggleUser
          , Toggles.value <| getBool "show.user" model.dictConfig
            ]
        [ Html.text "Mock User" ]

```

**Comment by debois** [comment]
It actually does, it just happens that the color of the track in the toggle is the same color as the header. 

We don't currently provide a good way of setting toggle colouring—upstream doesn't either—but you can control the color of a toggle-track in the header with CSS like this: 

    header div label .mdl-switch__track { 
      background-color: white !important;
    };

If your project doesn't have stand-alone CSS, use `Options.stylesheet`.
